### PR TITLE
Closes #1974 - Changing orientation while entering search engine details wipes entered data

### LINKED ISSUE #1974: Changing orientation while entering search engine details wipes entered data
This is on Pixel 2, Android O
STR:
Go to Settings -> Search Engine List -> Add Search engines
Enter details of new search engine
without saving or exiting, with the entered data shown, change orientation

Expected:
- Entered data survives
Actual:
Both fields are wiped clean

This bug is probably uncovered by #1924 fix.  Not sure this is a release blocker, but it would make users quite annoyed if they ever change the screen orientation for whatever reason during the add search engine step. @bbinto , @Sdaswani thoughts?

### PR DESCRIPTION
**Pull request by noloman**
Changing orientation while entering search engine details wipes entered data

### CODE REVIEW

**Comment by grubdragon** [comment]
Hey @noloman do check for others' PRs too, this bug was already solved :)

**Comment by noloman** [comment]
FML, my bad for not reading the already open PRs (this is my first PR and contribution). I thought the the pace of this project when approving PRs/merging would be higher, since the issue is already kinda old.

**Comment by Sdaswani** [comment]
Sorry @noloman we are a bit short staffed right now, our pace of review will pick back up soon.

**Comment by noloman** [comment]
no worries @Sdaswani we are here to help and contribute!

**Pull request closed without merging**
