### PR TITLE
match to leakCanary related gradle line to the leakCanary wiki

### LINKED ISSUE #2068: UI Test Process crashing, seems to be related to leakCanary
Locally the tests (For example, PageVisitTest) started failing with 'Process Crashed' error, and submitting the test on Google Testcloud shows following stacktrace.

java.lang.NoSuchMethodError: No direct method <init>(Lcom/squareup/leakcanary/WatchExecutor;Lcom/squareup/leakcanary/DebuggerControl;Lcom/squareup/leakcanary/GcTrigger;Lcom/squareup/leakcanary/HeapDumper;Lcom/squareup/leakcanary/HeapDump$Listener;Lcom/squareup/leakcanary/ExcludedRefs;)V in class Lcom/squareup/leakcanary/RefWatcher; or its super classes (declaration of 'com.squareup.leakcanary.RefWatcher' appears in /data/app/org.mozilla.focus.debug-1/base.apk:classes32.dex)

FATAL EXCEPTION: main
Process: org.mozilla.focus.debug, PID: 6468
java.lang.NoSuchMethodError: No direct method <init>(Lcom/squareup/leakcanary/WatchExecutor;Lcom/squareup/leakcanary/DebuggerControl;Lcom/squareup/leakcanary/GcTrigger;Lcom/squareup/leakcanary/HeapDumper;Lcom/squareup/leakcanary/HeapDump$Listener;Lcom/squareup/leakcanary/ExcludedRefs;)V in class Lcom/squareup/leakcanary/RefWatcher; or its super classes (declaration of 'com.squareup.leakcanary.RefWatcher' appears in /data/app/org.mozilla.focus.debug-1/base.apk:classes32.dex)
	at com.squareup.leakcanary.RefWatcherBuilder.build(RefWatcherBuilder.java:88)
	at com.squareup.leakcanary.AndroidRefWatcherBuilder.buildAndInstall(AndroidRefWatcherBuilder.java:57)
	at com.squareup.leakcanary.LeakCanary.install(LeakCanary.java:42)
	at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.java:36)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.support.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:382)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

### PR DESCRIPTION
**Pull request by npark-mozilla**
to fix #2068

### CODE REVIEW

**Comment by npark-mozilla** [comment]
@mcomella I changed it per https://github.com/square/leakcanary Getting Started section, and this seems to fix the issue locally.

**Comment by npark-mozilla** [comment]
Hmm, looks like changing the gradle command to releaseCompile fails the beta build, according to the TC log.

**Comment by npark-mozilla** [comment]
my theory is (i'm no gradle expert, so I could be wrong very much) that whatever defined by debugCompile gets overwritten by compile command that gets followed.

**Comment by npark-mozilla** [comment]
@mcomella even after adding compile commands for each build variant, it seems to fail some (13 total) unit tests as seen here: https://public-artifacts.taskcluster.net/QOmqaEh5TxanN3qYG9xxUg/0/public/tests/testFocusGeckoDebugUnitTest/classes/org.mozilla.focus.autocomplete.UrlAutoCompleteFilterTest.html#testAutocompletion

They are type of:
java.lang.NullPointerException
	at com.squareup.leakcanary.internal.LeakCanaryInternals.isInServiceProcess(LeakCanaryInternals.java:112)
	at com.squareup.leakcanary.LeakCanary.isInAnalyzerProcess(LeakCanary.java:145)
	at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.java:33)

any way we can get around this?

**Comment by ekager** [comment]
Hi @npark-mozilla ! Maybe we also need to add a testCompile line for the no-op version of leakCanary? 
https://github.com/square/leakcanary/issues/143

**Comment by npark-mozilla** [comment]
@ekager thanks! it seems my computer is possessed.  #2068 occurs only inside my ~/**GitRepo**/focus-android folder.  If I move the focus-android folder anywhere, even into other folders, I don't see the error. I recloned and deleted all hidden files insite GitRepo, and invalidated cache, but still see this error inside this specific folder.  But this seems to fix it.  I wonder how often others see this issue though.

**Comment by npark-mozilla** [comment]
LeakCanary is backed out for now, closing.

**Pull request closed without merging**
