### PR TITLE
Import strings from L10N repository.

### PR DESCRIPTION
**Pull request by ahunt**

### CODE REVIEW

**Comment by ahunt** [comment]
This doesn't build, I'll need to investigate that first.

**Comment by ahunt** [comment]
The issue is caused by "%\@" being included in about_content in values-ur/strings.xml, which confuses AAPT's string replacement checker.

This appears as "%@" in the input .po file.

**Comment by pocmo** [comment]
I think we saw that before when someone just reused the iOS string without  looking. Just fix the string manually in strings.xml (if you know how, for some languages that might be hard). Then we can land this and ping delphine/flod to get the source string fixed.

**Comment by ahunt** [comment]
flod fixed the string in pontoon, I've updated the import and everything works again!

**Pull request merged**
