### PR TITLE
Don't run nightly/beta UI tests on all pushes to the repo

### PR DESCRIPTION
**Pull request by jcristau**
We're only interested in these tasks on-push for the "level 3" branches,
i.e. main and releases_v*; development branches shouldn't run these
tasks.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by jcristau** [comment]
Sorry I think I need to look at this more.

**Comment by AaronMT** [comment]
I have no problem with beta removal as that matches Fenix, but I have a concern about ensuring Nightly, when generated, has the right taskgraph job to execute the test targets as sanity checks. The taskgraph should have the nightly job
https://github.com/mozilla-mobile/focus-android/blob/main/automation/taskcluster/androidTest/flank-x86-start-test.yml#L41

**Comment by AaronMT** [comment]
@jcristau I'm likely going ahead with the same UI test job environment change / job rename on Focus that I did on Fenix. If you'd like to proceed with this before-hand as it touches `taskcluster/ci/ui-test/kind.yml`

**Review by JohanLorenzo — APPROVED** [review]
I remember we wanted to run UI test on arbitrary branches because of scope issues. At that time, there was some heavy development related to these tests. 

That said, we now can target such tests with `try_task_config.json` like this one (untested): 

```json
{
    "tasks": [
        "ui-test-arm-nightly"
    ],
    "version": 1
}
```

Plus it caused more issues with bump PR that run on arbitrary branches. So I agree that we stop running UI tests on all pushes.

**Pull request merged**
