### PR TITLE
Redesign Context menu - Closes #2686

### LINKED ISSUE #2686: Redesign menu & dialog – Context menu
Old:

New:

Specs:

### PR DESCRIPTION
**Pull request by moyheen**
Here's a screenshot of the changes.

screenshot_1528279897

### CODE REVIEW

**Comment by moyheen** [comment]
@ekager I'm not sure why the CI was not triggered when I opened the PR.

**Comment by pocmo** [comment]
@brampitoyo Please review screenshot :)

**Comment by ekager** [comment]
Hey @brampitoyo when you get a chance, could you review this screenshot? We can start to merge UX updates now. Thanks!

**Comment by ekager** [comment]
Thanks @moyheen !

**Pull request merged**
