### PR TITLE
Don't process main frame requests (#35)

### PR DESCRIPTION
**Pull request by ahunt**
This also upgrades to the non-deprecated version of shouldInterceptRequest.
That means we're now firmly locked to Android 5+.

### CODE REVIEW

**Comment by pocmo** [comment]
I think that's fine. In the UI layer I am also using some Android 5+ features. In the security section of the Android docs they mention that WebView has some security flaws in Android 4.4 and lower - so we probably shouldn't go lower as we are loading random resources from the web.

**Comment by pocmo** [comment]
Is the blocking of main frame requests the reason why I had problems loading Google services?

**Comment by ahunt** [comment]
@pocmo Do you have specific sites that didn't work? I would've expected all google sites to break, but current builds seem to work for me.

**Comment by pocmo** [comment]
I only remember that several images wouldn't load on google.com (like the daily doodle). But this seems to work now.

**Pull request merged**
