### PR TITLE
For #7248: Align espresso-contrib version to other espresso libraries.

### LINKED ISSUE #7248: Upgrade espresso-contrib to 3.4.0
espresso-contrib is pinned in `build.gradle`[1] on an old alpha of a several year old release and should be upgraded to latest stable (3.4.0)[2]

[1] https://github.com/mozilla-mobile/focus-android/blob/main/app/build.gradle#L333
[2] https://developer.android.com/jetpack/androidx/releases/test

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

Fixes #7248

### CODE REVIEW

**Review by ionutbedregeanu — APPROVED** [review]

**Comment by AaronMT** [comment]
Thanks but one thing, please don't upgrade Flank at this time as I have it pinned on a version that works with our daily reporting in Slack. The newer releases changed the XML structure for JUnit reporting which we can't parse yet.

**Comment by mcarare** [comment]
@AaronMT I upgraded Flank because of the `BufferUnderflowException ` that was supposed to be fixed in the newer version. Not sure how to solve that error without upgrading.

**Comment by AaronMT** [comment]
Mentioned on Slack, but let's hold off for now. Thanks.

**Comment by mcarare** [comment]
Closing this as not planned.

**Pull request closed without merging**
