### PR TITLE
Android 8.1 / SDK 27

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Comment by pocmo** [comment]
Some unit tests are failing and this seems to be caused by Robolectric not being able to find resources anymore. We might need to wait for a new Robolectric release.

**Comment by pocmo** [comment]
Robolectric 3.5.1 was released and with that it can find our resources again. Some other tests needed to be adapted to work with it (and the new SDK version).

**Comment by pocmo** [comment]
* The build on taskcluster stopped because there's a new license that needs to be accepted.

* Travis is currently super slow and I'm still waiting for the response if the build is passing.

**Comment by pocmo** [comment]
SessionManagerTest seems to be the one that hangs in automation.

**Comment by mcomella** [comment]
@pocmo How did you fix the hanging tests?

**Comment by pocmo** [comment]
@mcomella Oh, I thought I pinged you on Slack about that - but I can't find the message anymore. Weird. Anyhow, upgrading Robolectric to 3.7.1 seems to have solved this problem. I also updated the build tools to 27.0.3 (was 27.0.2 before) but I think this didn't change anything - except that I had to fix some additional lint and checkstyle issues.

**Comment by pocmo** [comment]
@mcomella Oh, and watch out - the newest SDK / build tools create APKs in a different directory structure. Scripts depending on a hard-coded path might break, e.g. #2181

**Pull request merged**
