### PR TITLE
Increase the expire date of is_fenix_default_browser telemetry

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
https://github.com/mozilla-mobile/focus-android/issues/6299
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### CODE REVIEW

**Comment by ionutbedregeanu** [comment]
# Request for Data Collection Renewal
`mozilla_products:`
   `is_fenix_default_browser`

 1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/focus-android/pull/5303

2) When will this collection now expire?
      - 2023-02-01

3) Why was the initial period of collection insufficient?
      - This is a foundational metric that will be used for future analysis.

**Comment by rocketsroger** [comment]
> # Request for Data Collection Renewal
> 
> `mozilla_products:` `is_fenix_default_browser`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5295: Add metrics for other Mozilla products. #5303](https://github.com/mozilla-mobile/focus-android/pull/5303)
> 
>     2. When will this collection now expire?
>        
>        * 2023-02-01
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is a foundational metric that will be used for future analysis.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by rocketsroger — APPROVED** [review]

**Comment by ionutbedregeanu** [comment]
Could not GET 'https://repo.gradle.org/artifactory/jcenter/org/gradle/kotlin/gradle-kotlin-dsl-plugins/2.1.4/gradle-kotlin-dsl-plugins-2.1.4.module'.

**Comment by jonalmeida** [comment]
@Mergifyio backport releases_v97.0 releases_v96.0

**Pull request merged**
