### PR TITLE
Bug#1885 Correct comment grammar

### PR DESCRIPTION
**Pull request by harisankerPradeep**
Corrected comment grammar.

### CODE REVIEW

**Comment by mcomella** [comment]
Hey @harisankerPradeep – thanks for getting in contact with us on IRC! Sorry we missed you – we're usually around PST working hours M-F.

The Taskcluster failure is actually our fault – it's an intermittent that slipped through the cracks. fwiw, to check for yourself, you can click "Details" -> "Run logs" and read that to identify the failure. In this case:
```
FindBugs rule violations were found. See the report at: file:///opt/focus-android/app/build/reports/findbugs/findbugs.html
```

You can find any "build artifacts" (i.e. report files) under the "Run artifact" tab, where you can see public/findbugs/findbugs.html, which will take us to https://public-artifacts.taskcluster.net/ED8CsSbdQ8Onn7f1L-8ZQw/0/public/findbugs/findbugs.html where we'll find the unrelated error.

By the way, sorry it took so long to get back to you – we're having a colocated team meeting and our schedule has been a bit crazy. I'll try to be better about that this week.

If you'd like to keep hacking with us, maybe you'd be interested in #1712? If so, write a comment there so we (and others!) know that you're working on it!

**Comment by harisankerPradeep** [comment]
@mcomella, I would love to keep hacking with the team. However, bug #1712 seems taken. Is there something else you'd suggest for me :)

**Comment by mcomella** [comment]
Perhaps #1899?

**Comment by harisankerPradeep** [comment]
Sure, thanks!

Regards,
Harisanker Pradeep,
Second Year Undergraduate,
Dept Of Engineering Physics,
IIT Madras, Chennai

**Pull request merged**
