### PR TITLE
For #7965 - Handle Cookie Banner in Focus

### LINKED ISSUE #7927: The homescreen is displayed briefly before the new onboarding
## Steps to reproduce
1. Have a local Focus Nightly build installed.
2. Open it, and observe the new onboarding.

### Expected behavior
After the app is opened, the first screen of the new onboarding is displayed.

### Actual behavior
After the app is opened, the homescreen is displayed briefly, then the first screen of the new onboarding - please see the short video below.

### Device information
* Android device: Xiaomi Mi8 Lite (Android 10), Lenovo tablet M10 (Android 10), Samsung Galaxy Note 8 (Android 9)
* NOT reproducible on Google Pixel 6 (Android 13), Oppo Reno 6 (Android 12)
* Focus version: local Focus Nightly build 108.0a1

Screenshot_5

* Logcat: [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/9877406/logcat.txt)

https://user-images.githubusercontent.com/40694158/198232028-35027b20-ffd8-4223-a4bf-6bd5e7203c2b.mp4

### LINKED ISSUE #7965: Cookie Banner handling Focus
@jeffreygee Thank you for the design !

**1.Settings part** 
This is the GeckoView interface for Cookie banner 
>
     * Represents settings options for cookie banner handling.
    enum class CookieBannerHandlingMode(val mode: Int) {
      
         * The feature is turned off and cookie banners are not handled
        DISABLED(0),

         * Reject cookies if possible
        REJECT_ALL(1),

         * Reject cookies if possible. If rejecting is not possible, accept cookies
        REJECT_OR_ACCEPT_ALL(2),
    }
<filepath>

Synthesising the Figma design we will have the following 3 scenarios:

1)If the 'Auto cookie banner consent' is not checked 'Further reduce cooke banners' item will be invisible and value for Cookie banner conform GeckoView interface will be   DISABLED(0).
2) If the 'Auto cookie banner consent' is checked 'Further reduce cooke banners' item will be visible and unchecked the value for Cookie banner conform GeckoView interface will be   REJECT_ALL(1).
3)If the 'Auto cookie banner consent' is checked 'Further reduce cooke banners' item will be visible and checked the value for Cookie banner conform GeckoView interface will be  REJECT_OR_ACCEPT_ALL(2).

PS : If the user unchecked 'Auto cookie banner consent'  'Further reduce cooke banners' will become unchecked .
When the user enters first in the App the value will be DISABLED(0) first case.

https://user-images.githubusercontent.com/8118371/200337796-3f80d7c0-cd1b-4f59-aa82-985670617c6f.mp4

Screenshot 2022-11-07 at 16 50 23

When the cookie banner option is disabled, the summary text for preference will be Off, and when the cookie banner option is reject_or_accept_all or reject_all, it will be On.

 

This is the initial ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1797561

**2.Cookie banner panel part**
   1)If the CookieBannerHandleMode is reject_all or reject_or_accept_all, I show the toggle. If the site has no exception, the toggle will be true.

 

 2) If the CookieBannerHandleMode is disabled, the toggle and all the cookie banner section will be hidden.

 

3)If the user sets the toggle to false, I'm going to add the site to the exception list with the value MODE_DISABLED.

 

4)If the site doesn't have a cookie banner and CookieBannerHandleMode is reject_all, or accept_all, I will show the section but not the toggle.

### PR DESCRIPTION
**Pull request by iorgamgabriel**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #7965
Fixes #7927

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
In general it looks good to me!
Are we going to create a separate PR for adding telemetry?

**Comment by iorgamgabriel** [comment]
# Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?
  * How users interact with the cookie banners handling feature.
2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? 
  * This data will help us understand how the cookie banners handling feature is used.
3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
  * There are no other alternatives. 
4. Can current instrumentation answer these questions?
  * No. 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. 
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
When the cookie banners handling setting page is visited  | Category 2 - interaction data |https://bugzilla.mozilla.org/show_bug.cgi?id=1797561
Which setting is selected | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1797561

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
  * https://dictionary.telemetry.mozilla.org/apps/fenix 
7. How long will this data be collected? Choose one of the following:
  * Until version 119. Renewal then may be decided.
8. What populations will you measure?
  * All channels, all locales, all countries  that the feature is active for.
9. If this data collection is default on, what is the opt-out mechanism for users?
  * Default Glean SDK opt-out mechanism. 
10. Please provide a general description of how you will analize this data.
  * Glean and Amplitude. 
11. Where do you intend to share the results of your analysis?
  *  Only on Glean, Amplitude, and with mobile teams. 
12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
   * No third-party tools.

**Comment by rocketsroger** [comment]
> # Request for data collection review form
> 
> All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.
> 
>     1. What questions will you answer with this data?
> 
> 
>     * How users interact with the cookie banners handling feature.
> 
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
>     * This data will help us understand how the cookie banners handling feature is used.
> 
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * There are no other alternatives.
> 
> 
>     4. Can current instrumentation answer these questions?
> 
> 
>     * No.
> 
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.    
>        Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> When the cookie banners handling setting page is visited 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1797561
> Which setting is selected 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1797561
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * https://dictionary.telemetry.mozilla.org/apps/focus_android
> 
> 
>     7. How long will this data be collected? Choose one of the following:
> 
> 
>     * Until version 119. Renewal then may be decided.
> 
> 
>     8. What populations will you measure?
> 
> 
>     * All channels, all locales, all countries    that the feature is active for.
> 
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * Default Glean SDK opt-out mechanism.
> 
> 
>     10. Please provide a general description of how you will analize this data.
> 
> 
>     * Glean and Amplitude.
> 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
>     * Only on Glean, Amplitude, and with mobile teams.
> 
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
>     * No third-party tools.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by version 119

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Comment by rocketsroger** [comment]
Please make sure to update the data-review URL in metrics.yaml before landing this.  Thanks

**Pull request merged**
