### PR TITLE
Renew telemetry expiring in 106

### PR DESCRIPTION
**Pull request by iorgamgabriel**
Tests,Screenshots and Accessibility not needed 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by iorgamgabriel** [comment]
# Request for Data Collection Renewal
### Renew for 1 year
Total: 20
———
`browser.is_default`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - Browser usage we want to understand

———
`browser.locale_override`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - The locale that differs from the system locale if a user specifically overrides it for the app we want to understand

———
`browser.search.with_ads`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - Records counts of SERP pages with adverts displayed we want to understand

———
`browser.search.ad_clicks`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - Records clicks of adverts on SERP pages we want to understand
    
———
`browser.search.in_content`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - Records the type of interaction a user has on SERP pages we want to understand  

———
`mozilla_products.has_fenix_installed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5303

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    - We want to understand  if Fenix is installed on the users's device  

———
`settings_screen.whats_new_tapped`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5096

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand how many times a user has clicked
      on whats new button from settings screen.

———
`shortcuts.shortcuts_on_home_number`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5189
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand the number of shortcuts the user has on home screen.

———
`shortcuts.shortcut_opened_counter`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5189

2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand how many times a user has opened a website from a shortcut in the home screen.

———
`shortcuts.shortcut_added_counter`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5189
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand  how many times a user has added a website to shortcuts.

———
`shortcuts.shortcut_removed_counter`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5189
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand how many times a user has removed a website from shortcuts.

———
`tracking_protection.toolbar_shield_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand how many times a user has opened the tracking protection settings panel from the toolbar.

———
`tracking_protection.tracking_protection_changed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the setting for enhanced tracking protection.

———
`tracking_protection.tracker_setting_changed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the advertising tracker protection state.

———
`tracking_protection.has_social_blocked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the setting for enhanced tracking protection
      at least once.

———
`tracking_protection.has_advertising_blocked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the setting for enhanced tracking protection
      at least once.

———
`tracking_protection.has_analytics_blocked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the setting for enhanced tracking protection
      at least once.

———
`tracking_protection.has_content_blocked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5163
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand if the user has changed the setting for enhanced tracking protection
      at least once.

———
`preferences.user_theme`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5526
    
2) When will this collection now expire?
    - 119

3) Why was the initial period of collection insufficient?
    -We want to understand when the user changes app theme.

**Comment by Mugurell** [comment]
Drive by comment: Saw that the updated `data-reviews` sections from `metrics.yaml` were modified to point to the request comment. They should be updated after the data approval to link to the approval.

**Comment by iorgamgabriel** [comment]
Done @Mugurell

**Review by rocketsroger — COMMENTED** [review]
Don't forget to add this PR's link in `data_reviews:` section.

**Comment by rocketsroger** [comment]
> # Request for Data Collection Renewal
> ### Renew for 1 year
> 
> Total: 20 ——— `browser.is_default`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Issue #4901: Update metrics for data review on initial metrics #5065 (comment)](https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Browser usage we want to understand
> 
> 
> ——— `browser.default_search_engine`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Issue #4901: Update metrics for data review on initial metrics #5065 (comment)](https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Browser usage we want to understand
> 
> 
> ——— `browser.locale_override`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Issue #4901: Update metrics for data review on initial metrics #5065 (comment)](https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * The locale that differs from the system locale if a user specifically overrides it for the app we want to understand
> 
> 
> ——— `browser.search.with_ads`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #4967 - Record search / ads providers appearing in search results #4968 (comment)](https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Records counts of SERP pages with adverts displayed we want to understand
> 
> 
> ——— `browser.search.ad_clicks`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #4967 - Record search / ads providers appearing in search results #4968 (comment)](https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Records clicks of adverts on SERP pages we want to understand
> 
> 
> ——— `browser.search.in_content`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #4967 - Record search / ads providers appearing in search results #4968 (comment)](https://github.com/mozilla-mobile/focus-android/pull/4968#issuecomment-879256443)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Records the type of interaction a user has on SERP pages we want to understand
> 
> 
> ——— `mozilla_products.has_fenix_installed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5295: Add metrics for other Mozilla products. #5303](https://github.com/mozilla-mobile/focus-android/pull/5303)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We want to understand  if Fenix is installed on the users's device
> 
> 
> ——— `settings_screen.whats_new_tapped`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5058: Add Glean telemetry for what's new opened from settings. #5096](https://github.com/mozilla-mobile/focus-android/pull/5096)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand how many times a user has clicked
>        on whats new button from settings screen.
> 
> 
> ——— `shortcuts.shortcuts_on_home_number`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For 5056: Add Telemetry for Shortcuts. #5189](https://github.com/mozilla-mobile/focus-android/pull/5189)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand the number of shortcuts the user has on home screen.
> 
> 
> ——— `shortcuts.shortcut_opened_counter`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For 5056: Add Telemetry for Shortcuts. #5189](https://github.com/mozilla-mobile/focus-android/pull/5189)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand how many times a user has opened a website from a shortcut in the home screen.
> 
> 
> ——— `shortcuts.shortcut_added_counter`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For 5056: Add Telemetry for Shortcuts. #5189](https://github.com/mozilla-mobile/focus-android/pull/5189)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand  how many times a user has added a website to shortcuts.
> 
> 
> ——— `shortcuts.shortcut_removed_counter`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For 5056: Add Telemetry for Shortcuts. #5189](https://github.com/mozilla-mobile/focus-android/pull/5189)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand how many times a user has removed a website from shortcuts.
> 
> 
> ——— `tracking_protection.toolbar_shield_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand how many times a user has opened the tracking protection settings panel from the toolbar.
> 
> 
> ——— `tracking_protection.tracking_protection_changed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the setting for enhanced tracking protection.
> 
> 
> ——— `tracking_protection.tracker_setting_changed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the advertising tracker protection state.
> 
> 
> ——— `tracking_protection.has_social_blocked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the setting for enhanced tracking protection
>        at least once.
> 
> 
> ——— `tracking_protection.has_advertising_blocked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the setting for enhanced tracking protection
>        at least once.
> 
> 
> ——— `tracking_protection.has_analytics_blocked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the setting for enhanced tracking protection
>        at least once.
> 
> 
> ——— `tracking_protection.has_content_blocked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5057: Add Telemetry for Tracking Protection. #5163](https://github.com/mozilla-mobile/focus-android/pull/5163)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand if the user has changed the setting for enhanced tracking protection
>        at least once.
> 
> 
> ——— `preferences.user_theme`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5519: Add telemetry for theme settings. #5526](https://github.com/mozilla-mobile/focus-android/pull/5526)
> 
>     2. When will this collection now expire?
>        
>        * 119
> 
>     3. Why was the initial period of collection insufficient?
>        -We want to understand when the user changes app theme.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by mcarare — APPROVED** [review]
code r+

Do not forget to add the new data review comment to the list.

**Comment by iorgamgabriel** [comment]
I added new data review comment to the list. @mcarare @rocketsroger

**Review by rocketsroger — APPROVED** [review]
🚢

**Pull request merged**
