### PR TITLE
Switch Tabs Using Toolbar Swipe Gesture

### LINKED ISSUE #7730: Swipe To Switch Tab
### Why/User Benefit/User Problem
Like the default firefox browser, the focus should also enable the swipe to switch tab feature. I don't see why the "focus" makes a difference in not including that behavior.

### What / Requirements
Swipe Gesture to switch tab Should be implemented

### PR DESCRIPTION
**Pull request by 4shutosh**
### Pull Request checklist
Fixes #7730 

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by 4shutosh** [comment]
I use `focus` daily while reading blogs and surfing through websites. I did the changes required for the swipe behavior, primarily for my use case. I understand this does not follow the ideal contribution guidelines. 

Please let me know if anything else is required. More than happy to do the changes and do the necessary for the good.

**Comment by 4shutosh** [comment]
Most of the pieces of code are referred and used from `fenix`. 

The introduced behaviour is as follows:

https://user-images.githubusercontent.com/53831987/192141418-b4b76f88-3d71-413a-aff5-3b47c9839341.mp4

**Comment by Mugurell** [comment]
Thank you for looking into this but such a change should be first discussed with Product and UX. We will bring this up.
Some engineering investigation is also needed to check whether this functionality should be uplifted to A-C and then shared by both projects instead of duplicating the code.

**Comment by iorgamgabriel** [comment]
We are not gonna land this pr , a decision was made by @rtestard . Too much risk of confusion with the back action and lack of alignment with what users coming from Chrome . Thank you very much @4shutosh .

**Comment by 4shutosh** [comment]
Thank you for considering 🙌🏻 

I agree with @cadeyrn, the main reason to implement this was my muscle memory being disrespected on `Focus`

**Pull request closed without merging**
