### PR TITLE
Correct status bar height on multiwindow

### PR DESCRIPTION
**Pull request by fercarcedo**
This PR solves the problem of the status bar height not adjusting when going from multiwindow to fullscreen or vice versa.

The solution consists of querying the status bar height on onResume since it's the callback we get when entering/leaving multiwindow, and we cannot remove the WindowInsets listener due to the fact that when resizing the window (such as, for example, when resizing to go fullscreen) we don't get any lifecycle callback (such as onStart or onResume), instead the listener gets triggered.

#2275

### CODE REVIEW

**Comment by pocmo** [comment]
detekt is complaining about a wildcard import:
https://taskcluster-artifacts.net/IdHSjVd3Rq-Kex_yRxpKlw/0/public/detekt/detekt-report.html

**Comment by fercarcedo** [comment]
The wildcard import is now removed

**Comment by pocmo** [comment]
LGTM. Found another issue and filed #2316.

**Comment by pocmo** [comment]
Due to a merge conflict I'm landing this separately in #2317

**Pull request closed without merging**
