### PR TITLE
For #3075 - Adds telemetry for search suggestions

### PR DESCRIPTION
**Pull request by boek**
| Event                                  | category | method                | object     | value  | extras.    |
|----------------------------------------|----------|-----------------------|------------|--------|------------|
| URL entered*                            | action   | type_url              | search_bar |        | `search_suggestion: true/false` |
| Enable Search Suggestion from prompt                            | action   | click              | search_suggestion_prompt |    true/false    |  |

* Modified existing event to include the `search_suggestion` extra.

# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**

* Are users enabling search suggestions
* Are users searching using provided search suggestions

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

* Having this data will allow us to better prioritize supporting suggestions on new search engines, or existing search engines that add suggestion support.

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

* Outside of the number of user reviews asking for this feature, we don't know the extent to how much users will use search suggestions. Telemetry seems like the best option for this.

4) **Can current instrumentation answer these questions?**

* Without new telemetry there will be no conclusive evidence to answer the questions

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* All data is Category 2.

6) **How long will this data be collected?**

* @mmccorks will permanently monitor this data.

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Re-dash queries + dashboards

9) **Where do you intend to share the results of your analysis?**

* Only on re-dash and with mobile teams.

### CODE REVIEW

**Comment by boek** [comment]
Waiting on a data review from: @fmarier

**Comment by fmarier** [comment]
BTW, you're using an older version of the form. The latest is at <https://github.com/mozilla/data-review/blob/master/request.md>.

Is there documentation somewhere which lists the telemetry that is collected by Focus? Will this be added to it?

What's the control mechanism to allow users to turn off telemetry in Focus? (i.e. question 8 in the latest request form)

**Comment by boek** [comment]
@fmarier Ah sorry!

To answer your immediate questions:

1. Yes, once this lands I will add it here: https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

2. For Focus it is enabled by default, with an easy opt-out in the settings menu. For Klar telemetry is disabled by default, with an easy opt-in in the settings menu.

Do these answer your questions?

**Comment by fmarier** [comment]
> 1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes, at https://github.com/mozilla-mobile/focus-android/wiki/Telemetry.

> 2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, in the settings menu.

> 3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

Yes, @mmccorks.

> 4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Category 2.

> 5) Is the data collection request for default-on or default-off?

Default ON.

> 6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No.

> 7) Is the data collection covered by the existing Firefox privacy notice?

Yes.

> 8) Does there need to be a check-in in the future to determine whether to renew the data?

No, permanent.

**Pull request merged**
