### PR TITLE
Bug 1805256 - Adds the legacy-id to Glean internal and other pings

### PR DESCRIPTION
**Pull request by travis79**
This adds the legacy telemetry id to the Glean baseline, events, metrics, and the activation ping for the purpose of making historical analyses easier by allowing connecting of data between the two side-by-side systems.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
lgtm.

Waiting to merge until we have a data review r+.

**Comment by travis79** [comment]
Thanks @jonalmeida! I'll post in the comments here once @eliserichards has had a chance to do the data-review.

**Comment by jonalmeida** [comment]
Two questions:
1. Do we want to upstream this and the previous patch?
2. Do we need to eventually revert the link between the legacy-id and the other telemetry?

**Comment by travis79** [comment]
> Two questions:
> 
>     1. Do we want to upstream this and the previous patch?

I just checked and yes, this would be good to get into v109 with the other patch.

>     2. Do we need to eventually revert the link between the legacy-id and the other telemetry?

No, the only consequence of this is that it creates a link between a users historical legacy telemetry data and the new Glean data. It's all the same data once things get migrated so I don't see a need to revert this in the future, it can be removed when legacy telemetry is removed.

**Comment by gabrielluong** [comment]
Hey @travis79, we're tidying the opened PRs in this repo since this project moved to a new repository. It is now developed and maintained at: https://github.com/mozilla-mobile/firefox-android. Please reopen a new PR there if the issue is still relevant. Thank you!

**Comment by travis79** [comment]
> Hey @travis79, we're tidying the opened PRs in this repo since this project moved to a new repository. It is now developed and maintained at: [mozilla-mobile/firefox-android](https://github.com/mozilla-mobile/firefox-android). Please reopen a new PR there if the issue is still relevant. Thank you!

Definitely still relevant and important. I was hoping this might land before the migration. Let me see about reopening this there.

**Pull request closed without merging**
