### PR TITLE
Import Ebony strings - missing eo, lt, pl, tr

### PR DESCRIPTION
**Pull request by liuche**
Ran the new import script, was unable to import some locales (#1148), but also ran into some problems with mismatched number of placeholders:

```
Checking for placeholders in translation files...
 * [values-eo/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
 * [values-lt/strings.xml] missing placeholder in translation, key: preference_default_browser2
 * [values-pl/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
 * [values-tr/strings.xml] number of placeholders not matching, key: your_rights_content5
```

Not sure what should be done about these, but maybe the translations haven't been updated fully? Will make a note in the wiki when I find out what actions should be taken.

### CODE REVIEW

**Comment by pocmo** [comment]
```
* [values-eo/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
* [values-pl/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
* [values-tr/strings.xml] number of placeholders not matching, key: your_rights_content5
```

Those three are only warnings and not errors. And we should make this more obvious: I'm going to file a bug. Currently you can only see that by looking at the exit code (`echo $?`) if there are no other issues.

```
* [values-lt/strings.xml] missing placeholder in translation, key: preference_default_browser2
```

This is definitely an error. We can either contact Delphine directly or open a Bugzilla bug for the translators.

**Comment by liuche** [comment]
Removed the offending string, and also filed a bug for the missing placeholder:
https://bugzilla.mozilla.org/show_bug.cgi?id=1407344

I also added a commit to fix the taskcluster linting issue (removing an unused import), but there are other failures now:
`Building 39% > :app:mergeKlarWebviewCoverageAssetsergeKlarWebviewCoverageAssets
Could not merge source set folders: 
Error: java.nio.file.NoSuchFileException: /opt/focus-android/app/build/intermediates/assets/klarWebview/coverage/search/default
...
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /opt/focus-android/app/build/intermediates/assets/klarWebview/coverage/search/default
`

Any thoughts, @pocmo? The Buddybuild now builds fine, and the build error seems to be the same one that I saw in #1452 earlier.

**Comment by pocmo** [comment]
> I also added a commit to fix the taskcluster linting issue (removing an unused import)

I landed a patch for this today. If you rebase your branch then this one should be gone.

Looking at the other issue now...

**Comment by pocmo** [comment]
This looks like a gradle bug / race condition to me. I'll force-merge this and then see how the taskcluster build for master turns out.

**Pull request merged**
