### PR TITLE
Update Focus background

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
For #4923

Update Focus background
Figma design: https://www.figma.com/file/jgsM2hWimZbPmtUJn7IGIB/Focus-Landing-Page-Design-(Kate)?node-id=1648%3A87291

### CODE REVIEW

**Comment by jonalmeida** [comment]
I don't think we should add PNGs for the background. How would they look for different screen sizes? In landscape mode?

Using PNGs is also a large amount of memory that we would need to allocate.

Looking at the existing code, we use [a shape for the current gradient](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/res/drawable/background_gradient.xml). Since our new background is much more complex, wonder if we could export the SVG from the figma designs and use that as a background drawable. I haven't tested this out, but it's hunch. Happy to help try it out tomorrow if you run into problems. 🙂

**Comment by ionutbedregeanu** [comment]
> I don't think we should add PNGs for the background. How would they look for different screen sizes? In landscape mode?
> 
> Using PNGs is also a large amount of memory that we would need to allocate.
> 
> Looking at the existing code, we use [a shape for the current gradient](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/res/drawable/background_gradient.xml). Since our new background is much more complex, wonder if we could export the SVG from the figma designs and use that as a background drawable. I haven't tested this out, but it's hunch. Happy to help try it out tomorrow if you run into problems. 🙂

@jonalmeida Totally agree with you, but as you said our new background is more complex and I had some vector import errors. That's why I chose to import the background as png and use  a tool for lossless compression(pngcrush)
Maybe I should ask design team for some help

Screenshot 2021-07-13 at 15 50 22

**Comment by jonalmeida** [comment]
Spoke with UX, I think we're probably going to get a new resource for this since vector drawables don't support all those SVG properties.

**Comment by ionutbedregeanu** [comment]
> Spoke with UX, I think we're probably going to get a new resource for this since vector drawables don't support all those SVG properties. Let's punt on this until there's a solution that works for us/UX.

I made a new  update and seems all good

**Review by jonalmeida — APPROVED** [review]
Brilliant, looks so good! 🎉 ✨

**Pull request merged**
