### PR TITLE
Close #4801: Vendor service-telemetry into Focus

### LINKED ISSUE #4801: [crash] Focus crashes when accessing Settings
## Steps to reproduce
1. Install Focus through https://github.com/mozilla-mobile/focus-android/releases page or https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.focus.release/latest.
2. Open the app, tap on the main three-dot menu - Settings.

### Expected behavior
The app's settings page opens.

### Actual behavior
The app crashes continuously. Even when selecting to Close the app from the crash dialog.

### Device information
* Android device: Xiaomi Mi 8 Lite (Android 9), Samsung Galaxy Note 8 (Android 9)
* Focus version: 8.15.0, GV 88.0.20210412175251
* [logcat Focus.txt](https://github.com/mozilla-mobile/focus-android/files/6308483/logcat.Focus.txt)

https://user-images.githubusercontent.com/40694158/114661240-5ca76580-9cff-11eb-9249-f5d6faf0e0f8.mp4

### PR DESCRIPTION
**Pull request by jonalmeida**
Vendored `service-telemetry` component in here.

I reproduced the bug by enabling telemetry in the `TelemetryWrapper` (isTelemetryEnabled). The crash is no longer seen with this change.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Running the same gradle task locally, executes just fine:

```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalKlarX86Nightly'.
> Could not resolve all artifacts for configuration ':app:klarAarch64DebugCompileClasspath'.
   > Failed to transform artifact 'service-telemetry.aar (project :service-telemetry)' to match attributes {artifactType=jar}.
      > Execution failed for JetifyTransform: /opt/focus-android/service-telemetry/build/outputs/aar/service-telemetry-release.aar.
         > Failed to transform '/opt/focus-android/service-telemetry/build/outputs/aar/service-telemetry-release.aar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=/opt/focus-android/service-telemetry/build/outputs/aar/service-telemetry-release.aar, to=/opt/focus-android/service-telemetry/build/.transforms/ce149c29fd26cd30b2d1f457e14d712a/jetified-service-telemetry-release.aar)'. (Run with --stacktrace for more details.)

```

**Comment by pocmo** [comment]
Let's see if this is a permanent failure 🤔

**Comment by pocmo** [comment]
Okay, I'll download the Docker image and try locally.

**Comment by pocmo** [comment]
Locally this happens in Docker too.

@jonalmeida It seems to work with this change applied:

```diff
diff --git a/app/build.gradle b/app/build.gradle
index b9729faa..274dfc15 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -41,9 +41,11 @@ android {
             minifyEnabled true
             shrinkResources true
             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
+            matchingFallbacks = ['release']
         }
         debug {
             applicationIdSuffix ".debug"
+            matchingFallbacks = ['debug']
         }
         nightly {
             initWith release
@@ -170,7 +172,7 @@ dependencies {
     implementation "org.mozilla.components:ui-colors:$mozilla_components_version"

     implementation 'com.squareup.okhttp3:okhttp:3.14.1'
-    implementation project(path: ':service-telemetry', configuration: 'default')
+    implementation project(':service-telemetry')

     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
```

**Review by pocmo — APPROVED** [review]

**Comment by jonalmeida** [comment]
It worked, thank you!

**Pull request merged**
