### PR TITLE
Redesign menu & dialog - Multitasking Closes #2684

### LINKED ISSUE #2684: Redesign menu & dialog – Multitasking (list of tabs)
Old:

New:

Spec:

Just a note that the icon fill for the link icons follows our default value: `#f9f9fa` a80.

Whereas the icon fill for the erase icon remains `#ffffff` a100.

### PR DESCRIPTION
**Pull request by jayeshsolanki93**
Here's the screenshot:

screenshot_1528294593

### CODE REVIEW

**Comment by ekager** [comment]
@brampitoyo can you confirm screenshot?

**Comment by jayeshsolanki93** [comment]
Hi @brampitoyo @ekager 

 I forgot to change the delete svg. I see that #2697 fix that.

**Comment by ekager** [comment]
Yeah #2697 will update the icon! Thanks so much for your help! Could you explain where you got the value `#e6202340` from for `colorActiveSession`? I think it should be grey-10 10%, maybe @brampitoyo can help with the hex for that.

**Comment by jayeshsolanki93** [comment]
Hi! The hex #e6202340 is ink-80 90%. I figured the percent transparency to hex conversion from here https://stackoverflow.com/questions/15852122/hex-transparency-in-colors

I fixed on that particular value cause it matches closely with the color in the screenshot and grey-10 10% does not.

**Pull request merged**
