### PR TITLE
No issue: Removed redundant variable in UrlInputFragment

### PR DESCRIPTION
**Pull request by EmmanuelMess**
I don't know if this wasn't deleted for a reason, but it seems pretty redundant.

### CODE REVIEW

**Comment by boek** [comment]
Hey @EmmanuelMess, I'm not super familiar with the history of this bit of code. Could you explain a bit more what led you to this conclusion?

**Comment by boek** [comment]
Oh I see now what you mean! I'm gonna investigate a little and make sure wherever it ended up is still working as intended 👍

**Comment by colintheshots** [comment]
I think he's right. The old code looks like cruft and it duplicates functionality in the SearchSuggestionsViewModel.

**Comment by colintheshots** [comment]
TaskCluster is failing on an unused import.

**Comment by colintheshots** [comment]
Sorry, there's now a conflict to clear up. I'll merge after.

**Comment by EmmanuelMess** [comment]
Done!

**Comment by boek** [comment]
Thank you @EmmanuelMess!

**Pull request merged**
