### PR TITLE
Redesign page – Settings Closes #2687

### LINKED ISSUE #2687: Redesign page – Settings
Old:

New:

Specs:

Assets:

* [Language](https://cl.ly/1u413W0Y270J/Language.svg) (lacking our own, we’re using Material Icons, rounded style).
* [Privacy and Security](https://cl.ly/3P2a0V0J290X/Privacy%20Security.svg) should be the lock icon that we already show in the UI. @ekager, do we have that asset already stored somewhere? If not, the SVG is linked.
* [Search](https://cl.ly/2o2l3Q2u1Q1i/Search.svg) should also be in our repository already, but I’ve provided the SVG link, should it be required.
* [Mozilla](https://cl.ly/2N092t0q2l10/Mozilla.svg)

Just a note that the icon fill follows our default value: `#f9f9fa` a80.

### PR DESCRIPTION
**Pull request by andrewgiang**
settings
still_settings_img

### CODE REVIEW

**Comment by brampitoyo** [comment]
@andrewgiang looks good!

A couple of things to note:

* On “Language” and other modal menus and dialogues, make sure that the window theme matches. See #2686 for colour scheme. But maybe we’re going to fix this in another issue?
* Icons for “Privacy & Security” and “Search” should be coloured `#f9f9fa` a80 (at the moment, they look like pure white).
* The highlighted search engine entry inside “Search” → “Google” should have a background colour of `grey-10` a10 against the page background. In other words, it should be coloured slightly lighter than the page background. Sorry for not specifying this earlier!
* Inside the “Mozilla” section, the “Open in new tab” icons should be aligned to the right-side of the screen, rather than left.

Other than that, we’re good to go.

**Comment by andrewgiang** [comment]
> Icons for “Privacy & Security” and “Search” should be coloured #f9f9fa a80 (at the moment, they look like pure white).

The lock and privacy icons were already in the app and set as fill color android:fillColor="#ffffff" no alpha, should I update them app wide to be #f9f9fa a80?

**Comment by brampitoyo** [comment]
> The lock and privacy icons were already in the app and set as fill color android:fillColor="#ffffff" and no alpha, should I update them app wide to be #f9f9fa a80?

@andrewgiang The colour values shouldn’t be updated app-wide – only in this instance. Would that be possible?

The lock icon is already used in the URL bar, and the search icon in the URL bar when you type a query. In both of these cases, they should remain pure white.

**Comment by andrewgiang** [comment]
@brampitoyo Almost done with the changes, just a few more questions and remarks to your review notes.
> On “Language” and other modal menus and dialogues, make sure that the window theme matches. See #2686 for colour scheme. But maybe we’re going to fix this in another issue?

I think that this should probably be handled in that other issue so that duplicate work doesn't potentially happen.


> Inside the “Mozilla” section, the “Open in new tab” icons should be aligned to the right-side of the screen, rather than left.

Do you want the Open in new tab icons to follow the same icon sizing as the main settings screen? or revert to the old style?

Here is a comparison of the two options (new style on left, old style on right)
image



----

## Updated icons with consistent alpha and color 
screenshot_1528845879

## Updated highlighted state
screenshot_1528845974

**Comment by andrewgiang** [comment]
@brampitoyo 
16dp for old, 24dp for new

**Comment by brampitoyo** [comment]
@andrewgiang Right. What should’ve happened in the first place is that the Tab New icon – which is 16dp – should be fitted and centred inside a 24dp frame. This will give us the best, most accurate-looking icon.

Let’s use this file: [Tab New.svg](https://cl.ly/3z0S0J0z2S3c/Tab%20New.svg).

Thanks for making me aware of this little issue!

**Comment by ekager** [comment]
Hi @andrewgiang , did you update the file with the new svg @brampitoyo linked?

**Comment by andrewgiang** [comment]
@ekager Oops! Did not see that comment, updated just now.

**Comment by ekager** [comment]
@andrewgiang thanks! And could you post a final screenshot for @brampitoyo to approve?

**Comment by ekager** [comment]
Of the new tab specifically

**Comment by andrewgiang** [comment]
screenshot_1531590915

**Comment by ekager** [comment]
Thanks! @brampitoyo to confirm

**Comment by brampitoyo** [comment]
@ekager Looks good to me. Thanks @andrewgiang for all the work you’ve done on this issue!

**Comment by ekager** [comment]
Thanks @andrewgiang !

**Pull request merged**
