### PR TITLE
For #5785: Add telemetry for tabs count on app backgrounded.

### PR DESCRIPTION
**Pull request by mcarare**
# Request for data collection review form

**All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_
How many users are using multitabs and how.

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?_
This is needed to analyze feature usage and possible feature improvements or feature elimination.

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
This is the only way.

_4) Can current instrumentation answer these questions?_
No. We need a new specific event for a specific app feature.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._

_**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>App was sent to background</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/focus-android/issues/5785 </td>
   </tr>
</table>

_6) How long will this data be collected?  Choose one of the following:_
    Expiry for capturing data is set to "2022-11-01"

_7) What populations will you measure?_
All release channels and locales.

_8) If this data collection is default on, what is the opt-out mechanism for users?_
 Users can opt out of data collection by disabling Usage and technical data from Settings -> Privacy and security -> Data choices.

_9) Please provide a general description of how you will analyze this data._
 Glean 

_10) Where do you intend to share the results of your analysis?_
Only on Glean, mobile teams, and BD have internal access.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_
No.

### CODE REVIEW

**Comment by Mugurell** [comment]
Talked with Travis about this kind of events with the important data put in extra keys which proved problematic on Fenix who suggested that we could use here a [custom distribution](https://mozilla.github.io/glean/book/reference/metrics/custom_distribution.html) similar to:
```
tab-category-name:
  tab-count-name:
    type: custom_distribution
    description: >
      The count of tabs as the app enters the background
    range_min: 1
    range_max: 50
    bucket_count: 52
    histogram_type: linear
    unit: tabs
    bugs:
      - tbd
    data_reviews:
      - tbd
    notification_emails:
      - tbd@mozilla.com
    expires: tbd
```

**Comment by mcarare** [comment]
@travis79 Can you give a little more context to what `range_min`, `range_max`, `bucket_count' values mean. The documentation is not very clear in this matter. Thank you!

Also, should we implement this type of metric just for this count or for all tab count telemetry? Does this mean all other events that have extra_keys in Focus or Fenix should be refactored in the future?

**Comment by travis79** [comment]
> @travis79 Can you give a little more context to what `range_min`, `range_max`, `bucket_count' values mean. The documentation is not very clear in this matter. Thank you!
> 
> Also, should we implement this type of metric just for this count or for all tab count telemetry? Does this mean all other events that have extra_keys in Focus or Fenix should be refactored in the future?

Absolutely!  The `range_min` and `range_max` are the minimum and maximum tab counts that we will measure. Anything less than `min` or greater than `max` are still counted, but fall into an underflow and overflow "bucket". We still record the actual value to the "sum" property of the distribution for the purpose of calculating an average.  Then there is the `bucket_count`. This is the number of buckets that we are counting into. In the case that I provided  you, there are 52 buckets...  one each for the 1-50 tab counts we will accumulate to, and the remaining two become the underflow ( < 1 ) and the overflow ( > 50 ) buckets.

By way of example, imagine the shape of the data as a series of buckets with a number from 1 to 50 on them, each number represents the number of tabs a user has open. When the app records to this metric, it finds the bucket that corresponds to the number of tabs that were recorded and increments that bucket by 1. This allows you to record tabs from as many foreground sessions as you want and still be able to send them in the once-a-day metrics ping. It's just recording samples, tallying the counts for each "number of open tabs" recording. If the number of tabs doesn't match any of the buckets, then it falls into a special underflow or overflow bucket.

I think that this metric type is ideal for tab counts, there are still some tricky things about counting tabs that are tied to users behavior and when we actually count the tabs, but this gives us the best data to answer the questions we have about tab counts.  I would recommend that we start with this one count and let data-science validate that it's doing what we want and then it might be a good idea to discuss migrating the other tab counting metrics.

**Comment by mcarare** [comment]
@travis79 Thank you for the detailed explanation. 

I was confused about the `bucket_count`, because the documentation example mentions 50 buckets for a wide range of values:

`    range_min: 1
    range_max: 66355200
    bucket_count: 50
    histogram_type: exponential
    unit: pixels`

Correct me if I am wrong:

- For a linear histogram having fewer buckets than possible values would mean each bucket would correspond to a range instead of just a value. 

 - For our case, it's safe to say that we can also add 0 as the range_min, 50 as the max, and set the bucket count to 51? (otherwise, with 52 a bucket will be 'empty').

**Comment by travis79** [comment]
> @travis79 Thank you for the detailed explanation.
> 
> I was confused about the `bucket_count`, because the documentation example mentions 50 buckets for a wide range of values:
> 
> ` range_min: 1 range_max: 66355200 bucket_count: 50 histogram_type: exponential unit: pixels`
> 
> Correct me if I am wrong:
> 
>     * For a linear histogram having fewer buckets than possible values would mean each bucket would correspond to a range instead of just a value.
> 
>     * For our case, it's safe to say that we can also add 0 as the range_min, 50 as the max, and set the bucket count to 51? (otherwise, with 52 a bucket will be 'empty').

For "exponential" bucketing, a logarithmic scale is generated to determine the bucket "widths". In the case of "linear", you are exactly right, having fewer buckets than possible values would create buckets that were more than "1 count" wide. 

Your suggestion of `min=0, max=50, count=51` would work fine. There is a "simulator" at the bottom of the Glean doc page for custom distributions where you can try out the bucketing: https://mozilla.github.io/glean/book/reference/metrics/custom_distribution.html?kind=linear&lower-bound=0&upper-bound=50&bucket-count=51&data-options=log-normally-distributed

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
> _1) What questions will you answer with this data?_ How many users are using multitabs and how.
> 
> _2) Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?_ This is needed to analyze feature usage and possible feature improvements or feature elimination.
> 
> _3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_ This is the only way.
> 
> _4) Can current instrumentation answer these questions?_ No. We need a new specific event for a specific app feature.
> 
> _5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._
> 
> _**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_
> Measurement Description 	Data Collection Category 	Tracking Bug #
> App was sent to background 	Category 2 	https://github.com/[/issues/5785](https://github.com/mozilla-mobile/focus-android/issues/5785)
> 
> _6) How long will this data be collected? Choose one of the following:_ Expiry for capturing data is set to "2022-11-01"
> 
> _7) What populations will you measure?_ All release channels and locales.
> 
> _8) If this data collection is default on, what is the opt-out mechanism for users?_ Users can opt out of data collection by disabling Usage and technical data from Settings -> Privacy and security -> Data choices.
> 
> _9) Please provide a general description of how you will analyze this data._ Glean
> 
> _10) Where do you intend to share the results of your analysis?_ Only on Glean, mobile teams, and BD have internal access.
> 
> _12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_ No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by 2022-11-01

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+

**Review by travis79 — APPROVED** [review]
data-review+

**Review by ionutbedregeanu — APPROVED** [review]

**Pull request merged**
