### PR TITLE
Added a RefWatcher to all fragments(#2045) 

### PR DESCRIPTION
**Pull request by grubdragon**
Fragments in existence being AddToHomescreenDialogFragment, BrowserFragment, DownloadDialogFragment, FirstrunFragment, InforFragment, UrlInputFragment, WebFragment

### CODE REVIEW

**Comment by Sdaswani** [comment]
@grubdragon thanks for your contribution - we will definitely review this PR, but we may be a bit delayed given our short staffing for the next few weeks.

**Comment by Sdaswani** [comment]
@grubdragon we still haven't had a chance to look at this - it may be a few more weeks, sorry!

**Comment by pocmo** [comment]
LeakCanary has been removed from the repository due to other issues. So we can't merge this currently. I'm going to close this PR.

Nevertheless thank you for your help here. I assume the refwatcher didn't find any issues with the current code base?

**Comment by grubdragon** [comment]
As far as I remember :)
@noloman  that's a cool idea, maybe when leakyCanary is back :)

**Pull request closed without merging**
