### PR TITLE
Update automation account user in .taskcluster.yml

### PR DESCRIPTION
**Pull request by bhearsum**
We rotated this fairly recently.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@mergifyio refresh

**Comment by jonalmeida** [comment]
@bhearsum this PR seems to be stuck with your change, do you know what we should be doing next?

**Comment by bhearsum** [comment]
Oh, I thought this was merged already. @jcristau - anything else blocking here?

**Comment by jcristau** [comment]
No, we should merge this. I wonder what's going on with the CI here.

**Pull request merged**
