### PR TITLE
Removed unused string resources; Closes #2407

### LINKED ISSUE #2407: Removed unused string resources
pinging @boek to fill the following out:

**Why**

**What**

**Acceptance Criteria (how do I know when I’m done?)**

### PR DESCRIPTION
**Pull request by daivat15**
Closes issue [#2407](https://github.com/mozilla-mobile/focus-android/issues/2407).

The additions are just spaces that have crept into the translations' files.

### CODE REVIEW

**Comment by boek** [comment]
Hey @daivat15, thanks for picking this up! This looks good, I'm just going to make sure the changes persist after we import/export from the l10n repository 👍

**Comment by daivat15** [comment]
@boek What is the status of the review?

**Comment by daivat15** [comment]
@boek There you go! It has been fixed.

**Comment by boek** [comment]
Hey @daivat15,

My apologies, our strings were in a weird state. Could you fix the merge conflicts one more time and I'll get this merged in.

**Comment by boek** [comment]
@daivat15 that would be great. Sorry to make you duplicate your work. Let me know if there is anything I can do to help

**Pull request closed without merging**
