### PR TITLE
remove ARM compile and upload on taskcluster X86 build task

### PR DESCRIPTION
**Pull request by npark-mozilla**

### CODE REVIEW

**Comment by npark-mozilla** [comment]
to address #2953

**Comment by npark-mozilla** [comment]
Also addresses #2952

**Comment by npark-mozilla** [comment]
@pocmo will remove the test for the simulator.  Firebase always ran UI tests on both sim and device for a while - thinking that there might be something that requires testing on both. if not, then we'll stop the run on the sim.

**Comment by pocmo** [comment]
@npark-mozilla Ah, I see! If there are different architectures x86/ARM used on Firebase then you may need the different builds to be able to install them.

**Comment by npark-mozilla** [comment]
@pocmo wait, let me revert above comment - one other reason why it runs on both sim and device is that the tablet (nexus 9) is only available in simulator form in Google firebase.  so I think we need both run, on both webview/geckoview test.

**Pull request merged**
