### PR TITLE
Using color resource for inactive text for URL EditText hint

### PR DESCRIPTION
**Pull request by ekager**
Talked to @antlam about this and he wanted the URL input hint text color to match other inactive text color (50% white) which I added as a color resource in a previous PR.

### CODE REVIEW

**Comment by ekager** [comment]
@antlam can you confirm the correct color? :)

**Comment by antlam** [comment]
We should make 50% FFFFFF the inactive color. 

whatever code that is... :)

**Comment by ekager** [comment]
screen shot 2017-08-02 at 1 03 10 pm
@antlam It looks a little dark to me. Is this what you want?

**Comment by ekager** [comment]
We are going to work on this color tomorrow in person!

**Comment by ekager** [comment]
We figured out the right 50% hex :)

**Pull request merged**
