### PR TITLE
Fix UITest Failures in Firebase

### PR DESCRIPTION
**Pull request by npark-mozilla**
Use back key instead of matching by description
Match new title text on Open In dialog

### CODE REVIEW

**Comment by npark-mozilla** [comment]
Also fixes #2207

**Comment by npark-mozilla** [comment]
From the latest test result, the screenshoterror is caused by Espresso not being ready, and not exactly sure why WebViewDataTest is failing. it seems that the file is not created?

**Comment by pocmo** [comment]
LGTM 👍

**Comment by pocmo** [comment]
Oh man - next run failed because of another intermittent.. :)

https://tools.taskcluster.net/groups/Q8ETRxVLQUaerIjozs1-0g/tasks/QBd5IETPQ8apu_nEth0I-A/runs/0/logs/public%2Flogs%2Flive.log

**Pull request merged**
