### PR TITLE
For #5305: Allow menu to stretch up to 314dp width.

### PR DESCRIPTION
**Pull request by mcarare**
Before and after the fix, for the language presented in #5305

### CODE REVIEW

**Comment by mcarare** [comment]
@Delphine This would fix the issue with important locales, and it would be the same behaviour Fenix has.

**Comment by mcarare** [comment]
cc @brampitoyo

**Comment by Delphine** [comment]
Thanks for the help here. Please note though that the last string on the screenshot being truncated, and isn't comprehensible that way.

**Comment by brampitoyo** [comment]
@mcarare @Delphine Let me know if any UI help is needed here. This decision should also apply to Fenix, if we do make another change.

**Comment by mcarare** [comment]
UX approved this approach: https://github.com/mozilla-mobile/focus-android/issues/5305#issuecomment-913896455

**Comment by Delphine** [comment]
> Thanks for the help here. Please note though that the last string on the screenshot being truncated, and isn't comprehensible that way.

Thanks for the help! I misstated that the last string on the screenshot was truncated as well, because it's not :) This LGTM now, thank you!

**Review by ionutbedregeanu — APPROVED** [review]

**Pull request merged**
