### PR TITLE
Make some static fields final

### PR DESCRIPTION
**Pull request by gaul**
Adding final prohibits modification and allows initialization of
primitive and String fields at compile time instead of runtime in
clinit:

https://developer.android.com/training/articles/perf-tips.html#UseFinal

Found via error-prone.

### CODE REVIEW

**Comment by Sdaswani** [comment]
Feel free to merge after CI is green.

**Comment by gaul** [comment]
@Sdaswani buddybuild never completed; how can I restart CI?

**Comment by Sdaswani** [comment]
@npark-mozilla how can we get BB to run CI on this PR? thanks for the assist.

**Comment by npark-mozilla** [comment]
Ah, it's because the PR is in gaul, instead of created directry as a branch in this repo.  There is a setting in Buddybuild that enables this as an exception, but I can't seem to find it. @liuche , I remember you fixed this for Emily right? Could you give us a help?

**Comment by mcomella** [comment]
This looks fine with BB: it just runs build distribution and UI tests and we can back it out of master if the UI tests fail.

**Comment by mcomella** [comment]
Thanks gaul!

**Pull request merged**
