### PR TITLE
For #5594: Also Stop GeckoSession when releasing acquired GeckoDisplay.

### PR DESCRIPTION
**Pull request by mcarare**

### CODE REVIEW

**Review by pocmo — APPROVED** [review]
That's an awesome find! 👍 

I verified that this is working locally and preventing the crash. You may end up with a not completely loaded page in Focus (which was also not loaded in the custom tab yet) if you are really fast. But that may still be better than crashing.

Since that seems to be a GeckoView bug I filed this here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1741899

Let's add a comment referencing the bug. :)

**Comment by mcarare** [comment]
Added a comment referencing the Bugzilla bug.

**Comment by pocmo** [comment]
Great. Let's land this to unblock other PRs.

**Comment by pocmo** [comment]
@Mergifyio backport backport releases_v95.0

**Pull request merged**
