### PR TITLE
Deleted WebURLFinder from utils and upgraded android mozilla-componen…

### LINKED ISSUE #2355: Use WebURLFinder from Utils Package
We are in the process of adding the WebURLFinder class to https://github.com/mozilla-mobile/android-components-utils and updating the library version. We should use WebURLFinder from the library when it's added.

### PR DESCRIPTION
**Pull request by shahbazahmed1269**
…ts to version 0.2.2. Fixes #2355.

### CODE REVIEW

**Comment by boek** [comment]
@shahbazahmed1269 Thanks for the contribution! Could you rebase master onto your branch and push it up and I'll get it merged :)

**Comment by shahbazahmed1269** [comment]
@pocmo Thanks. I couldn't update the branch as I am out for a while.

Do you have any other bug or feature in mind which I can work on?

**Comment by pocmo** [comment]
@shahbazahmed1269 Have a look at our issues labeled with [help wanted](https://github.com/mozilla-mobile/focus-android/labels/help%20wanted). Here are some ideas:

* If you like using a profiler and investigating the cause of things 🕵️ then maybe #2369 is a good choice
* #1973 is a nice little improvement to our search engine validation 🔍 
* If you enjoy polishing UI ✨ so that it follow specs then have a look at #1658
* Or if you did your computer science homework 💻  and want to order lists then maybe look at #1647.

**Comment by shahbazahmed1269** [comment]
@pocmo Awesome, thanks I'll have a look at them.

**Pull request merged**
