### PR TITLE
Bug 1599814 - Fix broken nightlies because 'mobile-3/b-linux is not a…

### PR DESCRIPTION
**Pull request by JohanLorenzo**
… valid decision workerPoolId!'

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Hey @mozilla-mobile/focus-codeowners ! Can we get this patch landed? Otherwise the next release won't work.

**Comment by JohanLorenzo** [comment]
ping @jonalmeida @colintheshots

**Comment by JohanLorenzo** [comment]
I cannot land this PR because it's awaiting on `Taskcluster (pull_request)` which is no more. @jonalmeida, could you change the required checks to wait on `Firefox CI (pull_request)` instead?

image

**Comment by jonalmeida** [comment]
Unfortunately, I don't have the permissions for this, but I think @colintheshots would.

**Comment by colintheshots** [comment]
> Unfortunately, I don't have the permissions for this, but I think @colintheshots would.

Firefox CI did not appear in the list of status checks available, but I did remove Taskcluster (pull request) from the required checks for now.

**Comment by colintheshots** [comment]
Oddly enough Firefox CI appeared after I removed the old check.

**Pull request merged**
