### PR TITLE
Fixes #3155:  Update UI tests to reflect search suggestion changes 

### LINKED ISSUE #3155: Update UI tests to reflect search suggestion changes
ChangeSearchEngineTest.java
URLMismatchTest.java
SettingsBlockToggleTest.java
SwitchLocalTest.java

### PR DESCRIPTION
**Pull request by rpappalax**

### CODE REVIEW

**Comment by colintheshots** [comment]
The TaskCluster build is failing on checkstyle for unused imports:

[ant:checkstyle] [ERROR] /opt/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java:12:8: Unused import - android.support.test.uiautomator.By. [UnusedImports]
[ant:checkstyle] [ERROR] /opt/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java:29:15: Unused import - junit.framework.Assert.assertEquals. [UnusedImports]
[ant:checkstyle] [ERROR] /opt/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java:144:11: 'for' is not followed by whitespace. [WhitespaceAround]
[ant:checkstyle] [ERROR] /opt/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java:15:8: Unused import - android.support.test.uiautomator.UiScrollable. [UnusedImports]

**Comment by boek** [comment]
@rpappalax Do you want to land this and then open another PR for 'Searching for Mozilla' later? :)

**Comment by boek** [comment]
Fixes #3155

**Comment by rpappalax** [comment]
@boek yea, we've had some other issues come up this week so i'll prob land whatever i have since to make the sprint though i believe the fix is largely the same.

**Pull request closed without merging**
