### PR TITLE
Override versionName for shipping builds

### PR DESCRIPTION
**Pull request by jcristau**
https://github.com/mozilla-mobile/focus-android/pull/6399 makes us pass the versionName to gradlew for beta/release builds, but we need to tell gradle to use it and override the default.

Code pretty much stolen from fenix.

### CODE REVIEW

**Comment by AaronMT** [comment]
re: ui-test-x86-beta

```Kotlin
java.lang.NullPointerException: context.packageManager.g…ckageName, 0).versionName must not be null
       FATAL EXCEPTION: main
Process: org.mozilla.focus.beta, PID: 12252
java.lang.NullPointerException: context.packageManager.g…ckageName, 0).versionName must not be null
	at org.mozilla.focus.utils.SupportUtils.getAppVersion(SupportUtils.kt:85)
	at org.mozilla.focus.utils.SupportUtils.getSumoURLForTopic(SupportUtils.kt:63)
	at org.mozilla.focus.tips.Tip$Companion.createFreshLookTip(TipManager.kt:67)
	at org.mozilla.focus.tips.TipManager.addFreshLookTip(TipManager.kt:168)
	at org.mozilla.focus.tips.TipManager.populateListOfTips(TipManager.kt:146)
	at org.mozilla.focus.tips.TipManager.getAvailableTips(TipManager.kt:158)
	at org.mozilla.focus.fragment.UrlInputFragment.updateTipsLabel(UrlInputFragment.kt:233)
	at org.mozilla.focus.fragment.UrlInputFragment.onViewCreated(UrlInputFragment.kt:357)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Review by jonalmeida — APPROVED** [review]
@jcristau this should work without us needing to fix the tests - "whats new" code is not consistent with Fenix so we need to have a proper versionName for debug builds too.

I've filed https://github.com/mozilla-mobile/android-components/issues/11763 to upstream the code for the two projects so we don't have these inconsistencies in the future.

**Comment by jonalmeida** [comment]
@Mergifyio refresh

**Comment by jcristau** [comment]
@mergifyio backport releases_v98.0

**Pull request merged**
