### PR TITLE
Revert 3687 fix3624

### PR DESCRIPTION
**Pull request by ekager**
Found a less complicated fix

### CODE REVIEW

**Comment by colintheshots** [comment]
Is there a reason why we're reverting a second time?

**Comment by ekager** [comment]
Making SettingsActivity's parent MainActivity fixes the original issue without the complexity of this fix.

**Comment by ekager** [comment]
And introduced new regressions like #3697

**Comment by colintheshots** [comment]
> Making SettingsActivity's parent MainActivity fixes the original issue without the complexity of this fix.

I'm not seeing that the fix does anything. Opening the launcher icon still erases the SettingsActivity with singleTask and the parent activity set the MainActivity. ParentActivityName, from my past experience, only helps with Up navigation.

**Comment by colintheshots** [comment]
> And introduced new regressions like #3697

It's a one-liner edge case. There's a fix in the PRs.

**Comment by colintheshots** [comment]
Per my conversation with @ekager, it seems her phone doesn't exhibit the original issue so the proposed fix isn't viable. Closing.

**Pull request closed without merging**
