### PR TITLE
For #5257: Do not show add to home menu item if pinning is not supported

### PR DESCRIPTION
**Pull request by mcarare**

### CODE REVIEW

**Review by pocmo — COMMENTED** [review]
I wonder why this is needed? The code used to use the legacy way of adding shortcuts if the new feature wasn't available, I thought (that was through a broadcast, I think?)

**Comment by mcarare** [comment]
`installShortCutViaManager` is used. And it does nothing when  `ShortcutManagerCompat.isRequestPinShortcutSupported(context)` is false. So instead of showing the dialog and do nothing, we do not show the menu item at all.

**Comment by pocmo** [comment]
Looks like the code I remembered was replaced with `ShortcutManagerCompat` here:
https://github.com/mozilla-mobile/focus-android/commit/342613b2be15ca788240219c9a0936bc80cd5d90#diff-55fc6ebddb489ebdaf2a980a5de4d2c80d1258354f693ba10eaaf927da8e1537

[The docs of `ShortcutManagerCompat`](https://developer.android.com/reference/androidx/core/content/pm/ShortcutManagerCompat?hl=en#requestPinShortcut(android.content.Context,%20androidx.core.content.pm.ShortcutInfoCompat,%20android.content.IntentSender)) say: _"On API <= 25 it creates a legacy shortcut with the provided icon, label and intent."_ So I wonder why this is not working. Or is just the check not working properly?

**Comment by pocmo** [comment]
Looks like this change was done in #1291 - but for no other reason than using the AppCompat implementation .... that doesn't work? 😅

**Comment by mcarare** [comment]
It seems it does not on some devices.

**Comment by mcarare** [comment]
Either way, `ShortcutManagerCompat` 's`requestPinShortcut` also checks for `isRequestPinShortcutSupported` and returns false.

**Comment by pocmo** [comment]
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/pm/ShortcutManagerCompat.java;l=148-169;drc=0d673a8ebdd62c3610c26c389dce9a41af280ebe

Hm, still curious which one we hit here, the permission?

**Comment by mcarare** [comment]
My guess is `queryBroadcastReceivers`, for some launchers.

**Review by ionutbedregeanu — APPROVED** [review]

**Comment by mcarare** [comment]
Talked with @pocmo offline, I opened a separate issue to further investigate failure to add shortcut: https://github.com/mozilla-mobile/focus-android/issues/5354.

**Comment by mcarare** [comment]
> What went wrong:
> Execution failed for task ':service-telemetry:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':service-telemetry:lintClassPath'.
   > Could not download lint-api-30.0.0.jar (com.android.tools.lint:lint-api:30.0.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/30.0.0/lint-api-30.0.0.jar'.
         > Premature end of Content-Length delimited message body (expected: 931,074; received: 524,288)`

**Pull request merged**
