### PR TITLE
Close #4528: Remove HttpUrlConnection and OkHttp usages

### LINKED ISSUE #4528: Make sure Focus uses GeckoViewFetchClient
If we use client implementations anywhere then it should be GeckoViewFetchClient.

### PR DESCRIPTION
**Pull request by jonalmeida**
The `SearchSuggestionsFetcher` can be removed in the future when we decide to use the awesomebar feature, for now, this removes all the other client usages from production code.

Haven't been able to run tests on the patch because of some local gradle errors:

<details>

```
[Robolectric] org.mozilla.focus.settings.SearchEngineValidationTest.URL timing out is not valid: sdk=28; resources=BINARY
Downloading from maven 
Downloading: org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
[WARNING] Unable to get resource 'org.robolectric:android-all:pom:Q-robolectric-5415296' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
Downloading: org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.pom from repository central at http://repo1.maven.org/maven2
Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.pom
[WARNING] Unable to get resource 'org.robolectric:android-all:pom:Q-robolectric-5415296' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.pom
Downloading: org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
[WARNING] Unable to get resource 'org.robolectric:android-all:jar:Q-robolectric-5415296' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
Downloading: org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.jar from repository central at http://repo1.maven.org/maven2
Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.jar
[WARNING] Unable to get resource 'org.robolectric:android-all:jar:Q-robolectric-5415296' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/Q-robolectric-5415296/android-all-Q-robolectric-5415296.jar

Unable to resolve artifact: Missing:
----------
1) org.robolectric:android-all:jar:Q-robolectric-5415296

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=Q-robolectric-5415296 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=Q-robolectric-5415296 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:android-all:jar:Q-robolectric-5415296

```

</details>

### CODE REVIEW

**Review by pocmo — APPROVED** [review]
LGTM. 👍

**Comment by jonalmeida** [comment]
I'm not sure what's happening here. [All the tests](https://firefoxci.taskcluster-artifacts.net/drwPB0YzQHKKSa6BOl7Lqw/0/public/tests/testFocusX86DebugUnitTest/classes/org.mozilla.focus.animation.TransitionDrawableGroupTest.html#testResetIsCalledOnAllItems) are failing when we initialize the fetch client in the TelemetryWrapper because we already have another GeckoRuntime created.

It doesn't seem like a race because all the tests are failing (consistently), so it's probably something not properly configured in.. Robolectric? I'm not sure.

```
java.lang.IllegalStateException: Only one GeckoRuntime instance is allowed
	at org.mozilla.geckoview.GeckoRuntime.<init>(GeckoRuntime.java:185)
	at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:488)
	at org.mozilla.focus.components.EngineProvider.getOrCreateRuntime(EngineProvider.kt:28)
	at org.mozilla.focus.components.EngineProvider.createClient(EngineProvider.kt:41)
	at org.mozilla.focus.Components$client$2.invoke(Components.kt:59)
	at org.mozilla.focus.Components$client$2.invoke(Components.kt:37)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.focus.Components.getClient(Components.kt)
	at org.mozilla.focus.telemetry.TelemetryWrapper.init(TelemetryWrapper.kt:266)
	at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.kt:49)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pocmo** [comment]
@jonalmeida I saw the same when the `GeckoRuntime` got created. `GeckoView` can't run on a plain JVM and we would need to mock it. That's why I created [TestFocusApplication](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/test/java/org/mozilla/focus/TestFocusApplication.kt) to inject a fake `Engine` for unit tests. We may need to do something similar for `Client` (or use an actual implementation without GeckoView) to avoid creating a `GeckoRuntime`.

**Comment by jonalmeida** [comment]
Thank you! I'll go with a client override for now and we can re-think this later. Fenix seems to use a component tree of nested mocks, but if we might want to do something else later.

**Pull request merged**
