### PR TITLE
Deleted WebViewURLFinder and its dependency, updated org.mozilla.components. Fixes #2355

### LINKED ISSUE #2355: Use WebURLFinder from Utils Package
We are in the process of adding the WebURLFinder class to https://github.com/mozilla-mobile/android-components-utils and updating the library version. We should use WebURLFinder from the library when it's added.

### PR DESCRIPTION
**Pull request by shikhart98**
Fixes #2355 

Deleted WebViewURLFinder and fixes its dependency in session manager, updated org.mozilla.components to 0.2.2 

Signed-off-by: Shikhar Tyagi <shikhart98@gmail.com>

### CODE REVIEW

**Comment by ekager** [comment]
Hey @shikhart98 ! Thanks for your contribution! Someone had already submitted a patch for this issue, so I'm going to close this PR, but feel free to ping me if you want help finding another issue to work on. :)

**Comment by shikhart98** [comment]
Hey Emily! Can you help me finding more issues to work on. I really want to
contribute to open source, I learnt android development recently and want
to try my hand out on amazing projects like Focus-Android.

**Comment by ekager** [comment]
Hey @shikhart98 :

**Comment by shikhart98** [comment]
Hi!

**Comment by ekager** [comment]
I edited and left a list of some help wanted issues above :)

**Comment by shikhart98** [comment]
Thanks for helping 😄

**Pull request closed without merging**
