### PR TITLE
For #6566 : Some spelling errors in the new onboarding card

### PR DESCRIPTION
**Pull request by indurs**
Files modified

1. focus-android/app/src/main/res/values/strings.xml

2. focus-android/app/src/main/res/values-en-rGB/strings.xml

The string onboarding_history_description has been changed

Co-Authored-By: Mugurell <Mugurell@users.noreply.github.com>

OnBoarding

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### CODE REVIEW

**Comment by ionutbedregeanu** [comment]
@indurs First of all thanks for your help. Regarding your changes some things needs to be updated.
We are having a bot(mozilla-l10n-automation-bot) to translate all the strings from `values/strings.xml` so we don't need add manually translations for all the supported languages.
The only thing we need to do when we are trying to update an existing string is to create a new string resource in `values/strings.xml` with the new value and the id suffixed with its iteration index.
E.g: 
String to be updated:    
` <string name="onboarding_history_description">One tap erases your browsing history and cookies — and stops ads from following your around.</string>`

Updated string:
` <string name="onboarding_history_description2">One tap erases your browsing history and cookies — and stops ads from following you around.</string>`

**Comment by indurs** [comment]
Thanks You @ionutbedregeanu for the info !!
Will update the values/strings.xml and commit.

**Comment by indurs** [comment]
@ionutbedregeanu , in that scenario we need to use the new string resource id right?
KeyFeatureCard(
                            iconId = R.drawable.ic_history,
                            titleId = R.string.onboarding_history_title,
                            descriptionId = R.string.onboarding_history_description
                        )
will be updted to 
KeyFeatureCard(
                            iconId = R.drawable.ic_history,
                            titleId = R.string.onboarding_history_title,
                            descriptionId = R.string.onboarding_history_description2
                        )

**Comment by ionutbedregeanu** [comment]
> @ionutbedregeanu , in that scenario we need to use the new string resource id right? KeyFeatureCard( iconId = R.drawable.ic_history, titleId = R.string.onboarding_history_title, descriptionId = R.string.onboarding_history_description ) will be updted to KeyFeatureCard( iconId = R.drawable.ic_history, titleId = R.string.onboarding_history_title, descriptionId = R.string.onboarding_history_description2 )

@indurs Yes

**Pull request closed without merging**
