### PR TITLE
Exit PiP when launched externally with Intents

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
For #6755

https://user-images.githubusercontent.com/11731652/160414226-cb05b442-a4eb-48fa-adb1-857061bcd100.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### CODE REVIEW

**Comment by rocketsroger** [comment]
From test it works.  But when I did the following:
1. open Focus and start streaming from youtube, set to full screen.
2. switch to desktop to trigger PiP.
3. open Fenix go to google.com, share to focus

Expected:
4. PiP dismissed, google.com opened.   Focus should be now showing in portrait orientation.

Actual:
4. PiP dismissed, google.com opened.  Focus stuck in landscape mode and doesn't matter how I rotate the device it won't switch to portrait mode.

**Comment by Mugurell** [comment]
> Actual: 4. PiP dismissed, google.com opened. Focus stuck in landscape mode and doesn't matter how I rotate the device it won't switch to portrait mode.

Sounds like a race between 
handling the new intent and 
exiting fullscreen which would trigger exiting immersive mode and unlocking the orientation,
similar to the https://github.com/mozilla-mobile/fenix/issues/24040 Fenix issue.

**Comment by ionutbedregeanu** [comment]
[New ticket](https://github.com/mozilla-mobile/focus-android/issues/6862) created for https://github.com/mozilla-mobile/focus-android/pull/6768#issuecomment-1082371091

**Comment by ionutbedregeanu** [comment]
@rocketsroger Can you help with an r here?

**Review by iorgamgabriel — APPROVED** [review]

**Pull request merged**
