### PR TITLE
Convert UI tests from Java to Kotlin

### PR DESCRIPTION
**Pull request by sv-ohorvath**
In an effort to fix old UI tests and bring them to the same standard and structure as the ones on Fenix, I started to convert all UI tests to kotlin, have one common custom ActivityTestRule and next I'll refactor each test class one by one.

### CODE REVIEW

**Comment by AaronMT** [comment]
This ready for review?

**Comment by sv-ohorvath** [comment]
> This ready for review?

@AaronMT yes, it is. Thank you!

**Review by pocmo — COMMENTED** [review]
* Pushing to a branch in the repository will run the UI tests (although that may not be needed yet)
* Looks like detekt complained about some style things: https://firefox-ci-tc.services.mozilla.com/tasks/XkW0GNMvScin-Et-3ryLWg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXkW0GNMvScin-Et-3ryLWg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3DbW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8c2thc3BhcmlcMTYxNjU3ODU4OFx1alArZEFOVmFpNGRvOXY1b1ZvNDZ2ZFcyVk5lMkljUUpwd0dMK3diZTRFPVxleUpqWlhKMGFXWnBZMkYwWlNJNmV5SjJaWEp6YVc5dUlqb3hMQ0p6WTI5d1pYTWlPbHNpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNlNXNTBjbUZ1WlhSWGFXdHBJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNlUzUmhkSE5FWVhOb1ltOWhjbVFpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhiR3hmYkdSaGNGOTFjMlZ5Y3lJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbVZuWlc1amFXRmZaR1VpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcG1iMk4xYzE5aGJtUnliMmxrWDJWdVp5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T20xdlltbHNaVjl5Wld4bFlYTmxjeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tOW1abWxqWlY5eVpXMXZkR1VpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcHdhRzl1WldKdmIydGZZV05qWlhOeklpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZEdWaGJWOXRiMk52SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkRzl2YkhSdmIyeGxaR2wwYjNJaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAyY0c1ZlkyOXljQ0lzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uWndibDlrWldaaGRXeDBJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmRuQnVYMnRwYm5Sdk1WOXdjbTlrSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkbkJ1WDJ0cGJuUnZNVjl6ZEdGblpTSXNJbUZ6YzNWdFpUcHRiM3BwYkd4cFlXNXpMV2R5YjNWd09tRnVaSEp2YVdRdFkyOXRjRzl1Wlc1MGN5MWtaWFpsYkc5d1pYSnpJaXdpWVhOemRXMWxPbXh2WjJsdUxXbGtaVzUwYVhSNU9tMXZlbWxzYkdFdFlYVjBhREF2WVdSOFRXOTZhV3hzWVMxTVJFRlFmSE5yWVhOd1lYSnBJbDBzSW5OMFlYSjBJam94TmpFMk5UYzJOelUzTmpnNExDSmxlSEJwY25raU9qRTJNVFkxTnpnMU5UYzJPRGdzSW5ObFpXUWlPaUk0WWpGR1RGUldjbE0xVTNGaFpDMXJNR0U1WVV4M2VUZG5RbXcxYjJ0VVYzbHJlakJmWTBWdmVtbFpRU0lzSW5OcFoyNWhkSFZ5WlNJNklrNUthMm9yYlRCamVUSjRTRkZoTWxwM2J5dENUV2RzWW1WVmRrTTNOMGt3Y0U5WGNGTkZOVGs0UkRBOUlpd2lhWE56ZFdWeUlqb2ljM1JoZEdsakwzUmhjMnRqYkhWemRHVnlMM2RsWWkxelpYSjJaWElpZlgwPQ

**Comment by sv-ohorvath** [comment]
> * Pushing to a branch in the repository will run the UI tests (although that may not be needed yet)

I will need some permissions to do that for the future work. In this case, yes it's not needed, they will still fail as before.

> * Looks like detekt complained about some style things: https://firefox-ci-tc.services.mozilla.com/tasks/XkW0GNMvScin-Et-3ryLWg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXkW0GNMvScin-Et-3ryLWg%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3DbW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8c2thc3BhcmlcMTYxNjU3ODU4OFx1alArZEFOVmFpNGRvOXY1b1ZvNDZ2ZFcyVk5lMkljUUpwd0dMK3diZTRFPVxleUpqWlhKMGFXWnBZMkYwWlNJNmV5SjJaWEp6YVc5dUlqb3hMQ0p6WTI5d1pYTWlPbHNpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNlNXNTBjbUZ1WlhSWGFXdHBJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNlUzUmhkSE5FWVhOb1ltOWhjbVFpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhiR3hmYkdSaGNGOTFjMlZ5Y3lJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbVZuWlc1amFXRmZaR1VpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcG1iMk4xYzE5aGJtUnliMmxrWDJWdVp5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T20xdlltbHNaVjl5Wld4bFlYTmxjeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tOW1abWxqWlY5eVpXMXZkR1VpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcHdhRzl1WldKdmIydGZZV05qWlhOeklpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZEdWaGJWOXRiMk52SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkRzl2YkhSdmIyeGxaR2wwYjNJaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAyY0c1ZlkyOXljQ0lzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uWndibDlrWldaaGRXeDBJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmRuQnVYMnRwYm5Sdk1WOXdjbTlrSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkbkJ1WDJ0cGJuUnZNVjl6ZEdGblpTSXNJbUZ6YzNWdFpUcHRiM3BwYkd4cFlXNXpMV2R5YjNWd09tRnVaSEp2YVdRdFkyOXRjRzl1Wlc1MGN5MWtaWFpsYkc5d1pYSnpJaXdpWVhOemRXMWxPbXh2WjJsdUxXbGtaVzUwYVhSNU9tMXZlbWxzYkdFdFlYVjBhREF2WVdSOFRXOTZhV3hzWVMxTVJFRlFmSE5yWVhOd1lYSnBJbDBzSW5OMFlYSjBJam94TmpFMk5UYzJOelUzTmpnNExDSmxlSEJwY25raU9qRTJNVFkxTnpnMU5UYzJPRGdzSW5ObFpXUWlPaUk0WWpGR1RGUldjbE0xVTNGaFpDMXJNR0U1WVV4M2VUZG5RbXcxYjJ0VVYzbHJlakJmWTBWdmVtbFpRU0lzSW5OcFoyNWhkSFZ5WlNJNklrNUthMm9yYlRCamVUSjRTRkZoTWxwM2J5dENUV2RzWW1WVmRrTTNOMGt3Y0U5WGNGTkZOVGs0UkRBOUlpd2lhWE56ZFdWeUlqb2ljM1JoZEdsakwzUmhjMnRqYkhWemRHVnlMM2RsWWkxelpYSjJaWElpZlgwPQ

Working on it.

**Review by pocmo — APPROVED** [review]

**Pull request merged**
