### PR TITLE
For #6566 : Some spelling errors in the new onboarding card

### PR DESCRIPTION
**Pull request by indurs**
Files modified
1. focus-android/app/src/main/res/values/strings.xml

2. focus-android/app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt

OnBoarding

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### CODE REVIEW

**Review by ionutbedregeanu — APPROVED** [review]

**Comment by indurs** [comment]
@ionutbedregeanu , I closed the previous PR and created this new one. Thank You

**Comment by ionutbedregeanu** [comment]
I will restart this pr because were some problems with the CI

**Comment by ionutbedregeanu** [comment]
CI still gets paused

**Comment by indurs** [comment]
@ionutbedregeanu , is there anything I need to do?

**Comment by ionutbedregeanu** [comment]
> @ionutbedregeanu , is there anything I need to do?

Done. Was my mistake. In order to merge your changes we need to create a new pr with your commits and close this one.
https://github.com/mozilla-mobile/focus-android/pull/6616

**Comment by indurs** [comment]
Great! Thank You !!

**Pull request closed without merging**
