### PR TITLE
For #7378: Upgrade lifecycle and core to latest versions.

### LINKED ISSUE #7378: Upgrade lifecycle, core to latest versions
We should upgrade these dependencies in Focus to match versions: 
https://github.com/mozilla-mobile/android-components/issues/12500.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

Fixes #7378
Fixes #7378
Fixes #7378
Fixes #7378

### CODE REVIEW

**Review by iorgamgabriel — APPROVED** [review]

**Comment by ionutbedregeanu** [comment]
Landing canceled until the updates are made also in AC

**Comment by jonalmeida** [comment]
When trying to compile this change with the AC PR, there are some API changes that we need to address too:
```
e: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt: (53, 28): Unresolved reference: ViewTreeSavedStateRegistryOwner
e: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt: (191, 9): Unresolved reference: ViewTreeSavedStateRegistryOwner
e: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt: (191, 51): Unresolved reference: ViewTreeSavedStateRegistryOwner
e: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt: (373, 9): Unresolved reference: ViewTreeSavedStateRegistryOwner

// Some warnings too
e: warnings found and -Werror specified
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt: (44, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt: (113, 22): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt: (115, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt: (194, 23): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt: (100, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt: (206, 23): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/InstalledSearchEnginesSettingsFragment.kt: (30, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/InstalledSearchEnginesSettingsFragment.kt: (50, 15): 'onCreateOptionsMenu(Menu, MenuInflater): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/InstalledSearchEnginesSettingsFragment.kt: (55, 15): 'onPrepareOptionsMenu(Menu): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/InstalledSearchEnginesSettingsFragment.kt: (85, 27): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt: (54, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt: (120, 34): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/RemoveSearchEnginesSettingsFragment.kt: (23, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/RemoveSearchEnginesSettingsFragment.kt: (39, 15): 'onCreateOptionsMenu(Menu, MenuInflater): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/RemoveSearchEnginesSettingsFragment.kt: (44, 15): 'onPrepareOptionsMenu(Menu): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/RemoveSearchEnginesSettingsFragment.kt: (79, 27): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt: (26, 9): 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: /Users/jalmeida/src/focus-android/app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt: (64, 22): 'onOptionsItemSelected(MenuItem): Boolean' is deprecated. Deprecated in Java
```

It looks like we're using the `savedstate` library from an indirect dependency (AndroidX Activity/Fragment). ~Maybe we want to make it explicit in our dependencies list?~ We need to be explicit because compiler is unsure which version of the API we're using Looks like this is the new API we need to use (1.2.0 is re-written in Kotlin):
```diff
diff --git a/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt b/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
index 78a4ff67..2f3b432e 100644
--- a/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
+++ b/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
@@ -50,7 +50,8 @@ import androidx.compose.ui.window.PopupProperties
 import androidx.core.view.ViewCompat
 import androidx.core.view.WindowInsetsCompat
 import androidx.lifecycle.ViewTreeLifecycleOwner
-import androidx.savedstate.ViewTreeSavedStateRegistryOwner
+import androidx.savedstate.findViewTreeSavedStateRegistryOwner
+import androidx.savedstate.setViewTreeSavedStateRegistryOwner
 import mozilla.components.support.ktx.android.util.dpToPx
 import org.mozilla.focus.R
 import org.mozilla.focus.R.color
@@ -188,7 +189,7 @@ internal class CFRPopupFullScreenLayout(

     init {
         ViewTreeLifecycleOwner.set(this, ViewTreeLifecycleOwner.get(container))
-        ViewTreeSavedStateRegistryOwner.set(this, ViewTreeSavedStateRegistryOwner.get(container))
+        setViewTreeSavedStateRegistryOwner(container.findViewTreeSavedStateRegistryOwner())
         GeckoScreenOrientation.getInstance().addListener(orientationChangeListener)
         anchor.addOnAttachStateChangeListener(anchorDetachedListener)
     }
@@ -370,7 +371,7 @@ internal class CFRPopupFullScreenLayout(
         GeckoScreenOrientation.getInstance().removeListener(orientationChangeListener)
         disposeComposition()
         ViewTreeLifecycleOwner.set(this, null)
-        ViewTreeSavedStateRegistryOwner.set(this, null)
+        setViewTreeSavedStateRegistryOwner(null)
         windowManager.removeViewImmediate(this)
     }

```

**Comment by jonalmeida** [comment]
While doing some testing in this build, I ran into a crash that I cannot reproduce on today's Focus Nightly build (I rebased this patch and the AC one to the latest `main` branch to ensure I am using the same GV version).

STR:
1. Build browser.
2. Load gumtree.com
3. 💥 

Crash link: https://crash-stats.mozilla.org/report/index/42d4cdac-1a3a-487f-bce0-d45ef0220819

```
java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
	at android.hardware.SystemSensorManager$BaseEventQueue.enableSensor(SystemSensorManager.java:792)
	at android.hardware.SystemSensorManager$BaseEventQueue.addSensor(SystemSensorManager.java:712)
	at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:209)
	at android.hardware.SensorManager.registerListener(SensorManager.java:832)
	at android.hardware.SensorManager.registerListener(SensorManager.java:739)
	at org.mozilla.gecko.GeckoAppShell.enableSensor(GeckoAppShell.java:636)
	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:677)
```

**Comment by Amejia481** [comment]
Same issue as above, I just tried to load cnn.com, attaching the logcat logs.

[focus.txt](https://github.com/mozilla-mobile/focus-android/files/9390346/focus.txt)

**Comment by mcarare** [comment]
I added direct dependencies to androidX fragment and lifecycle viewmodel (to avoid duplicate class).

**Comment by mcarare** [comment]
@jonalmeida @Amejia481 I can reproduce the crash also on `main`, you just have to use a device with at least Android 12.

Reproduced on a Pixel 4 with Android 13.

It seems strange that a value of 0 triggers this as the [documentation](HIGH_SAMPLING_RATE_SENSORS) states it is for values >200 Hz

**Review by jonalmeida — APPROVED** [review]
> @jonalmeida @Amejia481 I can reproduce the crash also on `main`, you just have to use a device with at least Android 12.
> 
> Reproduced on a Pixel 4 with Android 13.
> 
> It seems strange that a value of 0 triggers this as the [documentation](HIGH_SAMPLING_RATE_SENSORS) states it is for values >200 Hz
> 
> LE: https://bugzilla.mozilla.org/show_bug.cgi?id=1780557

Thanks - in that case, this looks good to me!

We're holding off on landing this in the 106 cycle for now to avoid risk in AC/Fenix, but once we can, let's land this!

**Comment by mcarare** [comment]
Note that 1.9.0 is the latest version of core, but it needs compile version to be at least 33.

**Comment by jonalmeida** [comment]
Removing 'do not land' this should be safe to land now with the 106 branch cut.

**Pull request merged**
