### PR TITLE
For #5728 integrate API for persistent tracking protection exceptions in private mode

### PR DESCRIPTION
**Pull request by Amejia481**
Related changes https://github.com/mozilla-mobile/focus-android/pull/5729

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

**Comment by pocmo** [comment]
@Amejia481 A-C 96 update landed. But there's a conflict to resolve here now.

**Comment by Amejia481** [comment]
I addressed the merged conflicts :)

**Comment by pocmo** [comment]
Looks like ktlint found some issues. I'll see if I can push a patch.

**Comment by Amejia481** [comment]
Thanks for addressing it :)

**Pull request merged**
