### PR TITLE
For #5058: Add Glean telemetry for what's new opened from settings.

### PR DESCRIPTION
**Pull request by mcarare**

### CODE REVIEW

**Comment by mcarare** [comment]
@travis79 Does this change need a data review?
On another note, the existing telemetry in Focus is implemented somewhat differently than Fenix, not sure what is the status of it. (is it collected? are there dashboards for them? ). Does it need revising?

**Comment by jonalmeida** [comment]
If we're adding new or modifying old telemetry, I think we need to add new Glean metrics. We want to eventually remove the `TelemetryWrapper` code when we have all the old events migrated over and validated that the Glean integration is accurate (when compared to the current service-telemetry data).

**Comment by mcarare** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_
How often do users open a whats new link from the settings screen.

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?_
Measure whether this feature is used by users and how often.

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
This is the only way.

_4) Can current instrumentation answer these questions?_
No. We need a new specific event for a specific app feature.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._

_**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Tp whatsnew button from settings</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/focus-android/issues/5058</td>
  </tr>
</table>


_6) How long will this data be collected?  Choose one of the following:_
Until 2022-08-17.

_7) What populations will you measure?_
All release channels and locales.

_8) If this data collection is default on, what is the opt-out mechanism for users?_
 Users can opt of of data collection by disabling Usage and technical data from Settings -> Privacy and security -> Data choices.

_9) Please provide a general description of how you will analyze this data._
 Glean 

_10) Where do you intend to share the results of your analysis?_
Only on Glean, mobile teams and BD have internal access.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_
No.

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
> _1) What questions will you answer with this data?_
> How often do users open a whats new link from the settings screen.
> 
> _2) Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?_
> Measure whether this feature is used by users and how often.
> 
> _3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
> This is the only way.
> 
> _4) Can current instrumentation answer these questions?_
> No. We need a new specific event for a specific app feature.
> 
> _5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._
> 
> _**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Tp whatsnew button from settings 	Category 2 	https://github.com/[/issues/5058](https://github.com/mozilla-mobile/focus-android/issues/5058)
> 
> _6) How long will this data be collected? Choose one of the following:_
> Until 2022-08-17.
> 
> _7) What populations will you measure?_
> All release channels and locales.
> 
> _8) If this data collection is default on, what is the opt-out mechanism for users?_
> Users can opt of of data collection by disabling Usage and technical data from Settings -> Privacy and security -> Data choices.
> 
> _9) Please provide a general description of how you will analyze this data._
> Glean
> 
> _10) Where do you intend to share the results of your analysis?_
> Only on Glean, mobile teams and BD have internal access.
> 
> _12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_
> No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the Glean Dictionary.

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the app settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection to end 2022-08-17

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by travis79 — APPROVED** [review]
My approval is for data-collection only, and does not cover code-review.

**Review by jonalmeida — APPROVED** [review]
Code review r+

**Pull request merged**
