### PR TITLE
For #6210 - Created a button on Http error page that will redirect the user to Privacy & Security

### PR DESCRIPTION
**Pull request by iorgamgabriel**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### CODE REVIEW

**Comment by iorgamgabriel** [comment]
Screenshot_20220214-162123

**Comment by iorgamgabriel** [comment]
Hi @jeffreygee ,
please take a look at this screen and make me a review from UX point of view. I added "Go to Privacy&Security" button . I changed the last sentence from " To change this setting or to learn more, go to Settings > Privacy & Security > Security."
to "To change this setting or to learn more:" .
Thank you very much !

**Comment by jeffreygee** [comment]
> 

I have pinged Brian on the content team for a quick tweak on the copy!

**Comment by jeffreygee** [comment]
> Hi @jeffreygee , please take a look at this screen and make me a review from UX point of view. I added "Go to Privacy&Security" button . I changed the last sentence from " To change this setting or to learn more, go to Settings > Privacy & Security > Security." to "To change this setting or to learn more:" . Thank you very much !

Hi @iorgamgabriel - after chatting with Channing and Brian, we think it's best to keep the previous/original user flow with a single CTA. In this proposed experience, the primary button takes user out of the task they invoked (head to settings instead of visit the site they're trying to access) and could cause confusion with the user. Happy to discuss further!

**Pull request closed without merging**
