### PR TITLE
The "back" action does not redirect the user correctly

### LINKED ISSUE #4395: URL Autocomplete - The "back" action does not redirect the user correctly
## Steps to reproduce
1. Open Firefox Focus and navigate to "Settings"/"Search"/"URL Autocomplete".
2. Tap on the "Learn More" SUMO link.
3. Tap on the "Back" of the device.
### Expected behavior
The user is sent back to "URL Autocomplete" section.
### Actual behavior
The user is sent to the first page.
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

Note:
It should be the same implementation as for "i" icon for "Add search engine" option.

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
For #4395
Open a custom tab for all "Learn more" pages to redirect the user to the settings screen when "back" button is pressed

https://user-images.githubusercontent.com/11731652/183594311-1bf2a7ae-6fac-42ac-8e4e-dacecd4a8e4b.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR:
1. click on `Show All Checks`,
2. click `Details` next to `build-focus-debug` or `build-klar-debug` for changes targeting Klar,
2. click `View task in Taskcluster`,
3. click the `Artifacts` row,
4. click to download any of the apks listed here which use an appropriate name for each CPU architecture.

### GitHub Automation
Fixes #4395

### CODE REVIEW

**Comment by Mugurell** [comment]
This PR refactors other settings also to use a custom tab (which makes reviewing a bit hard, would be nice to split the work in multiple commits) but I'm not sure this is the way to go.

Using a custom tab for the "Learn more" links is nice to give a popup like UX but it's a different UX than that of normal browsing with users not being able to see/edit the URL, not being able to switch between tabs (like the ones just opened for this sumo links) and different menu options.

Not convinced the ticket is a bug. The described issue is exact behavior seen on Fenix currently and the same behavior used for many similar scenarios in Focus.

**Comment by ionutbedregeanu** [comment]
> This PR refactors other settings also to use a custom tab (which makes reviewing a bit hard, would be nice to split the work in multiple commits) but I'm not sure this is the way to go.
> 
> Using a custom tab for the "Learn more" links is nice to give a popup like UX but it's a different UX than that of normal browsing with users not being able to see/edit the URL, not being able to switch between tabs (like the ones just opened for this sumo links) and different menu options.
> 
> Not convinced the ticket is a bug. The described issue is exact behavior seen on Fenix currently and the same behavior used for many similar scenarios in Focus.

This suggestion was made [here](https://github.com/mozilla-mobile/focus-android/issues/5316), but since Fenix has the same behaviour(opens a normal tab) maybe we should consider the current Focus behaviour also as expected

**Comment by Mugurell** [comment]
Because there are big implications with switching to use custom tabs I also tested on other browsers:
- Chrome - does not seem to have "Learn more" like links in settings
- Opera - has just a few with one in Settings -> VPN which when clicked opens a new tab which when closed returns the user to homescreen.
- DDG - has a "Learn more" button in `Settings -> Email protection` or `Settings -> App Tracking Protection` which when tapped will open a new settings like screen loading a html (don't know if live or bundled with the app)
`Settings -> Email Protection -> I have an Invite code` will open a new tab and if pressing back will close the app (feels like a bug)

**Comment by mcarare** [comment]
Feedback on this was requested from UX on https://bugzilla.mozilla.org/show_bug.cgi?id=1802253. 
Depending on the response, the work will be submitted to the new home of Focus, the https://github.com/mozilla-mobile/firefox-android repo.
Closing this as such.

**Pull request closed without merging**
