### PR TITLE
Implement beta dark mode

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
For #4992

[Fixed] Focus production use the same background as nightly
[Added] Background and logo for Focus Beta

### CODE REVIEW

**Comment by ionutbedregeanu** [comment]
@brampitoyo I noticed that in Figma we are using two different colors for menu #342F6D and #271948 and I'm not sure which is the correct one. Can you help me with that? Also the color used for menu should be used for dialogs and settings screen, am I right?

**Comment by brampitoyo** [comment]
@ionutbedregeanu The colour value that @Kate-Galetski has specified in the `Landing Page` document is the correct one: `Ink 10` `#342F6D`.

I’ve now updated all menus in the other two documents – `Product UI` and `Shortcuts` – to use the same value. Sorry for this oversight!

**Review by Amejia481 — APPROVED** [review]

**Comment by jonalmeida** [comment]
Ah, this change updated the debug icon and not the release ones. 🙂

**Comment by ionutbedregeanu** [comment]
> Ah, this change updated the debug icons as well and not the release ones. 🙂

[This pr](https://github.com/mozilla-mobile/focus-android/pull/5360) should fix this

**Pull request merged**
