### PR TITLE
Update to first Android Components 96.0 Nightly build

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
I don't have access to see the UI test failure, but it's very likely to be related to the AC changes to the tracking protection exception

**Comment by pocmo** [comment]
That patch is not in it yet. Triggered a new Nightly with it. Will update this PR here.

**Comment by pocmo** [comment]
Updated to newest 96.0 Nightly.

**Comment by jonalmeida** [comment]
> I don't have access to see the UI test failure, but it's very likely to be related to the AC changes to the tracking protection exception

Those failures are being fixed in https://github.com/mozilla-mobile/focus-android/pull/5756.

**Pull request merged**
