### PR TITLE
Add correct placeholder in lo strings ✌🏻

### PR DESCRIPTION
**Pull request by ekager**
Let's try this

### CODE REVIEW

**Comment by boek** [comment]
I think we just have to open a PR against mozilla-l10n/focus-android-l10n. Or this will get overwritten by @MickeyMoz. Gonna merge this in to see if it fixes TaskCluster though before we do it

**Comment by ekager** [comment]
Merged let's see how master looks and then decide the l10n repo strategy

**Comment by pocmo** [comment]
I wonder how this placeholder got in? MickeyMoz has been refusing to open PRs because of this. :)

**Comment by ekager** [comment]
Ahh. Okay should we revert and then just open an issue or tell l10n?

**Comment by ekager** [comment]
Oh just saw #2557 do we need to revert still?

**Comment by pocmo** [comment]
A new import should fix the issue. I'll trigger MickeyMoz so that you do not need to do it manually. :)

**Pull request merged**
