### PR TITLE
Update AndroidX testing libraries to the latest releases

### PR DESCRIPTION
**Pull request by rvandermeulen**
Was reverted back to 3.1.0-alpha4 in #7883. This is aiming to get it back to 3.4.0 again.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
OK, espresso-contrib 3.5.0 apparently fixes whatever issue is at play here. From what I can tell, this is a crash in the dex-test-parsing library (coming in from Flank I believe?). There's some upstream bugs that look possibly related (one specifically called out fixing a crash in Espresso 3.4.0), but it also doesn't appear that upstream Flank is staying up to date with that dependency. Anyway, if the current setup isn't actively hurting anything, we can probably just live with this until Espresso 3.5.0 ships.

**Comment by rvandermeulen** [comment]
Updating all of espresso to 3.5.0-beta01 is consistently hitting debug UI test failures in CustomTabTest
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:71)
	at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$5.invoke(CustomTabTest.kt:119)
	at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$5.invoke(CustomTabTest.kt:118)
	at org.mozilla.focus.activity.robots.CustomTabRobot$Transition.clickOpenInFocusButton(CustomTabRobot.kt:101)
	at org.mozilla.focus.activity.CustomTabTest.openCustomTabInFocusTest(CustomTabTest.kt:118)
    
```

**Comment by rvandermeulen** [comment]
@AaronMT Trying to update these libraries, I'm seeing a consistent CustomTabTest failure. Given that it's debug-only, is that pointing to a timing issue maybe?

**Comment by AaronMT** [comment]
Don't think so as there's a visible behavior difference watching the videos and how custom tabs intents are working here when they return to the browser, as it's supposed to load the custom tab : [Failure](https://storage.cloud.google.com/focus_android_test_artifacts/2022-10-29_01-19-00.579125_QGKv/matrix_0/Pixel2.arm-30-en_US-portrait-shard_2/video.mp4?authuser=1) (browser home-screen, empty URL bar focused) / [Pass](https://storage.cloud.google.com/focus_android_test_artifacts/2022-10-29_02-09-24.390280_rUhA/matrix_0/Pixel2.arm-30-en_US-portrait-shard_2/video.mp4?authuser=1). 

possibly some newer library differences in the intent building here [createCustomTabIntent](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt#L275) although I'm not familiar with this code, and it's also marked deprecated suppressed (maybe @mcarare has an idea?)

**Comment by mcarare** [comment]
It seems that the page crashes (or at least the browser tab is not opened) when pressing the "open in focus" button.
The deprecation annotation is related to the way we show the share button and the way we set the toolbar color. I will add a patch to update that to the new API but is not related to the test failure. 
The recent changes to the file, related to retrieving the package name also do not influence the test results.

Will look more into what is happening here.

**Comment by mcarare** [comment]
The failure occurs when upgrading `androidx.test:core` from 1.5.0-alpha01 to 1.5.0-alpha02.
In the release notes, there is no concrete code change, but it mentions:

> API changes
> 
> Modify ActivityScenario#launch to remove use of Bootstrap Activity API. This change should improve performance and stability of ActivityScenario#launch. ActivityScenario#getResult will now enforce that it can only be used with ActivityScenario#launchActivityForResult

**Comment by sv-ohorvath** [comment]
Thanks, @mcarare! I agree with your solution. For my part, feel free to remove the first steps before launching the custom tab activity, to avoid any more trouble.

> It seems like launching the new activity (when pressing "open in focus" button) clashes with the initial `launchActivity` with null params, used to open the initial browser page.
> 
> I suggest 2 paths to fix the tests :
> 
> * investigate the changes that make the interaction problematic
> * eliminate the overhead and keep the code that actually checks just the "open in focus" feature:
> 
> ```
>     fun openCustomTabInFocusTest() {
>         val customTabPage = getGenericTabAsset(webServer, 1)
> 
>         launchActivity<IntentReceiverActivity>(createCustomTabIntent(customTabPage.url))
>         customTab {
>             progressBar.waitUntilGone(waitingTime)
>             verifyPageURL(customTabPage.url)
>             openCustomTabMenu()
>         }.clickOpenInFocusButton {
>             verifyPageURL(customTabPage.url)
>         }
>     }
> ```
> 
> cc: @sv-ohorvath ,@AndiAJ

**Comment by rvandermeulen** [comment]
@mcarare Looks good now, thanks! I'll keep an eye out for the final releases of those AndroidX test libraries and update the PR when they're ready.

**Comment by rvandermeulen** [comment]
Opt and Debug UI tests are green with the final releases. I think this is ready to go!

**Review by jonalmeida — APPROVED** [review]
Rubber stamping to get this landed. Thanks all!

**Pull request merged**
