### PR TITLE
Fixes #3059 - Accept license for latest sdk / build tools

### LINKED ISSUE #3059: Update Docker File
I attempted to do this this week but couldn't get it to work because of local errors when running docker build. 

We need to update the Dockerfile to add new 28.0.1 build tools and android-28 sdk for #3053. It also includes an outdated Webview build type test that we need to update. 

We need to tag the version, instructions here: https://groups.google.com/a/mozilla.com/forum/#!searchin/mobile-all/Docker%7Csort:date/mobile-all/QF7nzVkEyUw/JkwbJB6LCwAJ

More Docker info here: https://github.com/mozilla-mobile/shared-docs/blob/master/docker_guide.md

### PR DESCRIPTION
**Pull request by boek**
Trying a docker build failed spotbugs, but I think that may be due to a different issue?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:spotbugs'.
> Failed to run Gradle SpotBugs Worker
   > Process 'Gradle SpotBugs Worker 2' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19m 38s
```

### CODE REVIEW

**Comment by boek** [comment]
spotbugs finished successfully locally

```
./gradlew spotbugs
...
BUILD SUCCESSFUL in 8m 43s
```

**Comment by boek** [comment]
image

Explains why this wasn't working on my laptop 🤷‍♂️ 😂

**Comment by boek** [comment]
https://hub.docker.com/r/mozillamobile/focus-android/tags/

Pushed the image and updated the taskcluster file 👍

**Comment by pocmo** [comment]
@boek There are some python scripts that generate tasks dynamically. Please make sure to add the version number there too. You should find them when searching for "mozillamobile/focus-android".

**Comment by pocmo** [comment]
Threre's also a second task in .taskcluster.yml :)

**Comment by boek** [comment]
@pocmo Ahah, that is good to know! Updated

**Pull request merged**
