### PR TITLE
Update production main background and launch icons

### PR DESCRIPTION
**Pull request by ionutbedregeanu**
For #5355 

Move all launch icons from debug to production
Move main page background from debug to production
Update nightly background

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
Thanks for fixing!

The icon seems bigger than the recommended icon size (this can affect Samsung's Android launcher, etc if we draw outside the margins), so maybe that's something @brampitoyo might know how we can resolve too.

Let's land this for now so at least we can correct the icons and background.

Screen Shot 2021-09-13 at 2 32 50 PM

**Comment by brampitoyo** [comment]
@jonalmeida Odd. I’m opening our Firefox and Focus icon assets side by side, and found that they both have identical margins from the side:

Screen Shot 2021-09-14 at 2 44 33 PM

Here are the two folders that I’m using for comparison. They both contain ready to use assets:
- Firefox `ic_launcher`: https://drive.google.com/drive/folders/12u1kRCAU62jLeaNdL9KHEhwdkd6i6ZMq
- Focus `ic_launcher`: https://drive.google.com/drive/folders/1Y8-0OaEALfYANdRlK-aF7TST5ldxnWyZ

Just to be doubly sure, I’ve also re-exported the Focus assets and re-checked them so they match Firefox’s.

**Comment by cadeyrn** [comment]
@brampitoyo Could you please clarify a few questions regarding the logo?

1. Do I see it correctly that the Focus logo was changed in v91 and will be changed again in v93 (with other colors)? Or is this a pre-release-only thing?
2. Is it really expected to have such a low contrast between logo and background? For me it's almost impossible to distinguish the bottom part of the logo from the background because it's almost the same color. See also #5180 for the same issue with the start screen background. Now the launcher icon has the same issue. Reducing / Removing contrasts seems to be Mozilla's new design philosophy (see also the Proton UI for desktop where some user interface elements like the address bar are almost invisible) but is it really a good idea for the brand logo?

**Comment by jonalmeida** [comment]
>     1. Do I see it correctly that the Focus logo was changed in v91 and will be changed again in v93 (with other colors)? Or is this a pre-release-only thing?

Yes, this is correct. That logo change was a previous iteration that we didn't intend to be the final version but it was released as part of 91.

**Comment by brampitoyo** [comment]
Just to confirm that @Kate-Galetski will be working on this logo contrast issue, although I might end up making the actual change in the production file and re-export them!

**Comment by brampitoyo** [comment]
@jonalmeida I’ve just darkened the logo background, from an old `Ink` value of `#202340`, to our darkest shade of `Ink 90` `#1d1133`.

The result should be a slightly improved contrast between the icon and its background.

You can find all the logo assets here: https://drive.google.com/drive/folders/1Y8-0OaEALfYANdRlK-aF7TST5ldxnWyZ

**Comment by ionutbedregeanu** [comment]
> @jonalmeida I’ve just darkened the logo background, from an old `Ink` value of `#202340`, to our darkest shade of `Ink 90` `#1d1133`.
> 
> The result should be a slightly improved contrast between the icon and its background.
> 
> You can find all the logo assets here: https://drive.google.com/drive/folders/1Y8-0OaEALfYANdRlK-aF7TST5ldxnWyZ

@brampitoyo In order to have a single source of truth, can you please update also in Figma?

**Pull request merged**
