### PR TITLE
MainActivityFirstrunTestRule: Skip first run screen.

### PR DESCRIPTION
**Pull request by pocmo**
The state of `AppStore` is determined on application start and therefore before `beforeActivityLaunched()` runs. So if we are in the `FirstRun` screen state then we skip that. We still set the preference additionally for further app launches.

### CODE REVIEW

**Comment by pocmo** [comment]
There are still failures on Firebase, even though that worked locally. I'll investigate.

**Comment by pocmo** [comment]
Oh, heh, now this broke `FirstRunDialogueTest` :D - I'll put up a fix for that.

**Comment by pocmo** [comment]
On Firebase I see failures in:
* `FirstRunDialogueTest`
* `openDownloadFileTest`
* `downloadNotificationTest`
* `cancelDownloadTest`

**Comment by pocmo** [comment]
>     * `FirstRunDialogueTest`

I pushed a fix for this one.

>     * `openDownloadFileTest`
>     * `downloadNotificationTest`
>     * `cancelDownloadTest`

Those pass for me locally. Let's see if they still fail in the next push.

**Comment by pocmo** [comment]
> This one hangs for me - while showing the notification tray. But I have been testing on a Pixel 4a. Let's see how it behaves in automation.

Ah, this only happened because there was another notification in my tabs tray. Once that was gone the test passed too.

**Comment by pocmo** [comment]
Still the three download tests failing in automation.

**Review by sv-ohorvath — APPROVED** [review]
LGTM, let's see if the checks pass.

**Pull request merged**
